integration_tests/ARM_SGP.jl, integration_tests/Bomex.jl, integration_tests/DYCOMS_RF01.jl, integration_tests/GABLS.jl, integration_tests/Rico.jl, integration_tests/Soares.jl, integration_tests/TRMM_LBA.jl, src/Turbulence_PrognosticTKE.jl
=> Fix dycoms bug, KM-KH typo

src/EDMF_Environment.jl, src/EDMF_Updrafts.jl, src/Turbulence_PrognosticTKE.jl, src/python_primitives.jl
- Adds type annotations to method arguments
- properly defines and uses `argwhere`
- Fixes a scope bug in `buoyancy`
=> Apply some bug fixes / fix translations

docs/Project.toml, docs/make.jl, docs/src/ReferenceStates.md, docs/src/References.md
This will be helpful to verify that the reference state profiles don't change too dramatically in #25.
=> Add reference state profile plots to docs

integration_tests/utils/Cases.jl, src/EDMF_Environment.jl, src/EDMF_Rain.jl, src/EDMF_Updrafts.jl, src/Forcing.jl, src/Grid.jl, src/Radiation.jl, src/ReferenceState.jl, src/Surface.jl, src/Turbulence.jl, src/Turbulence_PrognosticTKE.jl, src/turbulence_functions.jl
This PR adds some convenience methods for handling traversing the grid.
=> Add grid abstractions

.buildkite/pipeline.yml, integration_tests/Bomex.jl, integration_tests/Nieuwstadt.jl, integration_tests/Rico.jl, integration_tests/Soares.jl, integration_tests/utils/Cases.jl, src/turbulence_functions.jl, src/types.jl
I believe this fixes the Nieuwstadt case. This may also fix / improve other cases. cc @yairchn. Looking forward to re-try #25, #40, and #43.
=> Fix inversion height bug, read Ri bulk crit from namelist, add Nieuwstadt case

integration_tests/TRMM_LBA.jl, integration_tests/utils/Cases.jl, integration_tests/utils/compute_mse.jl, src/EDMF_Updrafts.jl, src/Turbulence.jl, src/Turbulence_PrognosticTKE.jl, src/Variables.jl
I'm hoping that this will fix the theta-L plots in our comparisons.
=> Apply theta-l bcs where it seems to be missing

integration_tests/ARM_SGP.jl, integration_tests/Bomex.jl, integration_tests/DYCOMS_RF01.jl, integration_tests/GABLS.jl, integration_tests/Nieuwstadt.jl, integration_tests/Rico.jl, integration_tests/Soares.jl, integration_tests/TRMM_LBA.jl, integration_tests/utils/variable_map.jl
=> Add mean temperature to mse tables / output plots

src/types.jl
=> Fix field locations

src/TurbulenceConvection.jl, src/types.jl
This PR makes a bit more use of `parse_namelist`.
=> use parse_namelist

src/Turbulence_PrognosticTKE.jl
This PR merges four updraft closures into a single function as part of the fuse operations task. 
It is a first step in replacing these functions with the point wise functions coded in ClimateMachine.
=> fuse updraft closures

integration_tests/utils/Cases.jl, src/EDMF_Environment.jl, src/EDMF_Updrafts.jl, src/Fields.jl, src/Grid.jl, src/Surface.jl, src/Turbulence_PrognosticTKE.jl, src/Variables.jl, src/turbulence_functions.jl
This PR should help make the transition to 1-based indexing much easier.
=> Abstract cent/face surface/toa indices

integration_tests/utils/parameter_set.jl, src/Turbulence_PrognosticTKE.jl, src/turbulence_functions.jl, src/types.jl
This should do it for being able to calibrate `entrainment_factor` while also using CLIMAParameters.jl
=> Move entrainment fact to climaparams method call

integration_tests/ARM_SGP.jl, integration_tests/Bomex.jl, integration_tests/DYCOMS_RF01.jl, integration_tests/GABLS.jl, integration_tests/Nieuwstadt.jl, integration_tests/Rico.jl, integration_tests/Soares.jl, integration_tests/TRMM_LBA.jl, integration_tests/utils/compute_mse.jl
=> Average profiles

integration_tests/ARM_SGP.jl, integration_tests/Bomex.jl, integration_tests/DYCOMS_RF01.jl, integration_tests/Nieuwstadt.jl, integration_tests/Rico.jl, integration_tests/Soares.jl, integration_tests/TRMM_LBA.jl, src/Operators.jl, src/TurbulenceConvection.jl, src/Turbulence_PrognosticTKE.jl, src/closures/perturbation_pressure.jl, src/turbulence_functions.jl, src/types.jl
this PR moves the nh_pressure computation to /closures folder
=> move nh_pressure computation to /closures folder 

integration_tests/ARM_SGP.jl, integration_tests/Bomex.jl, integration_tests/DYCOMS_RF01.jl, integration_tests/DryBubble.jl, integration_tests/GABLS.jl, integration_tests/Nieuwstadt.jl, integration_tests/Rico.jl, integration_tests/SP.jl, integration_tests/Soares.jl, integration_tests/TRMM_LBA.jl, integration_tests/life_cycle_Tan2018.jl, integration_tests/utils/compute_mse.jl
This should allow us to optionally, and safely, use in any of the nc files (les, scampy, tc, tc-main) in a more flexible way.
=> Add mse wrapper to make optional files flexible

integration_tests/utils/Cases.jl, src/EDMF_Environment.jl, src/EDMF_Updrafts.jl, src/Radiation.jl, src/Surface.jl, src/Turbulence_PrognosticTKE.jl, src/Variables.jl, src/closures/entr_detr.jl, src/closures/nondimensional_exchange_functions.jl, src/closures/perturbation_pressure.jl, src/microphysics_functions.jl, src/python_primitives.jl, src/surface_functions.jl, src/thermodynamic_functions.jl, src/turbulence_functions.jl
This PR deletes the artifacts made for directly translating from python
=> Remove some python primitives

integration_tests/ARM_SGP.jl, integration_tests/Bomex.jl, integration_tests/DYCOMS_RF01.jl, integration_tests/DryBubble.jl, integration_tests/Nieuwstadt.jl, integration_tests/Rico.jl, integration_tests/SP.jl, integration_tests/Soares.jl, integration_tests/TRMM_LBA.jl, integration_tests/life_cycle_Tan2018.jl, integration_tests/utils/generate_namelist.jl
This PR this is step towards removing sub stepping in the model
=> Set timestep to 3 sec for all simulations 

integration_tests/utils/generate_namelist.jl, integration_tests/utils/parameter_set.jl, src/Turbulence_PrognosticTKE.jl, src/turbulence_functions.jl
This PR adds standalone gradient Richardson number and turbulent Prandtl number functions that are called from compute_mixing_length. It is the first step to organizing mixing length function.
=> add Ri and Pr functions

src/Operators.jl, src/Turbulence_PrognosticTKE.jl
We shouldn't be traversing cell center indices when updating cell face data. This PR fixes this bug in the diagnostics
=> Fix diagnostics traversal

src/Turbulence_PrognosticTKE.jl
This PR adds aliases to shorten expressions
=> Add aliases to shorten expressions

README.md
I found myself looking where I recently wrote this down and couldn't find it. I figured that it might be useful in the docs somewhere.
=> Add table of prognostic/diagnostic vars

src/Turbulence_PrognosticTKE.jl
This PR takes a small pieces of #187.
=> Some update restructuring

src/Turbulence_PrognosticTKE.jl
This should hopefully help us get rid of `QL.new` / `T.new` etc.
=> Move diagnostics computations out of solve_updraft

utils/print_new_mse.jl
This may be useful for PRs where we have differences on the order of numerical precision.
=> Add info statements printing max Δmse

src/Operators.jl, src/Turbulence_PrognosticTKE.jl
It looks like there are a few other places where we hard-coded interpolations/derivatives, so we'll need to fix that up, too.
=> Remove `interp2pt`!

src/EDMF_Rain.jl, src/Operators.jl
I'm not exactly sure how this algo works, but it's currently accessing ghost points, and we're trying to avoid them. This PR adds a hack to avoid accessing ghost points.
=> Avoid accessing ghost points in Microphysics

src/Turbulence_PrognosticTKE.jl, src/types.jl
This PR peels off some pieces in #220. I'm hoping that these will just merge
=> Apply some bug fixes

src/ReferenceState.jl
This peels off a piece from #218.
=> Fix range in reference state construction

src/Turbulence_PrognosticTKE.jl
This PR merges the mixing length, the eddy diffusivities and the tke_buoy functions
=> Merge env rhs functions 

integration_tests/utils/Cases.jl, src/EDMF_Environment.jl, src/EDMF_Rain.jl, src/EDMF_Updrafts.jl, src/Grid.jl, src/Radiation.jl, src/ReferenceState.jl, src/Surface.jl, src/Turbulence_PrognosticTKE.jl, src/Variables.jl, src/turbulence_functions.jl
This PR fixes `indicies` -> `indices`.
=> Fix indices typo

integration_tests/utils/Cases.jl, src/EDMF_Rain.jl, src/Grid.jl, src/Radiation.jl, src/ReferenceState.jl, src/Variables.jl, src/turbulence_functions.jl
This PR removes `center_indices` and `face_indices` in preparation for #218
=> Remove center_indices and face_indices

integration_tests/utils/Cases.jl
=> Fix domain traversal and indexing to use real only

src/EDMF_Updrafts.jl
This PR fixes a bug that was found in #218. This is likely non-behavior changing, since the only impact (I think) will be that we're now spanning the full range of the grid in this loop.
=> Split face/center grid traversal

src/Turbulence_PrognosticTKE.jl
=> Fix index for face BC

src/Turbulence_PrognosticTKE.jl
=> Fix surface index for Buoyancy

src/Operators.jl
=> Fix ∇f2c operator bug

src/Operators.jl, src/Turbulence_PrognosticTKE.jl
=> Fix daul_c2f_upwind stencil

src/Turbulence_PrognosticTKE.jl
Another peel off from #218.
The passed variables live on cell faces and need to be interpolated to feed into the assigned cell center data.
=> Fix interpolation bugfix

src/Turbulence_PrognosticTKE.jl
=> Add use of interpolated field, use correct gradient

integration_tests/utils/compute_mse.jl, test/runtests.jl
See [this comment](https://github.com/CliMA/TurbulenceConvection.jl/pull/218#issuecomment-917149679)
=> Fix TC main coordinates in compute_mse

docs/src/ReferenceStates.md, integration_tests/utils/Cases.jl, integration_tests/utils/compute_mse.jl, src/EDMF_Environment.jl, src/EDMF_Rain.jl, src/EDMF_Updrafts.jl, src/Fields.jl, src/Forcing.jl, src/Grid.jl, src/NetCDFIO.jl, src/Operators.jl, src/Radiation.jl, src/ReferenceState.jl, src/Surface.jl, src/TurbulenceConvection.jl, src/Turbulence_PrognosticTKE.jl, src/Variables.jl, src/python_primitives.jl, src/turbulence_functions.jl
This PR switches over to using a ClimaCore.jl grid and changes some variable names
- `dz` -> `Δz`
- `z_half` -> `zc`
- `z` -> `zf`
I think that this should all work with [ClimaCore.jl's 173](https://github.com/CliMA/ClimaCore.jl/pull/173). We'll need to create a new branch to update to, or just point to a new SHA, maybe that's easier than creating new branches.
Since this PR changes `z_half` / `z` to `zc` and `zf`, we'll need a follow-up PR to change the names for the main branch.
=> Use ClimaCore grid

integration_tests/utils/Cases.jl, integration_tests/utils/main.jl, src/EDMF_Environment.jl, src/EDMF_Rain.jl, src/EDMF_Updrafts.jl, src/Forcing.jl, src/NetCDFIO.jl, src/Radiation.jl, src/Surface.jl, src/Turbulence_PrognosticTKE.jl, src/Variables.jl, src/types.jl
This PR does a global replace of
- `Gr` -> `grid`
-  `Ref` -> `ref_state`
=> Rename some variables

src/EDMF_Environment.jl
these two variables are computed in quadrature but are not used
=> cleanup quadrature

integration_tests/utils/Cases.jl
I didn't think that this would help us delete this much code, but 🎉!
=> Use generic methods in Cases.jl

src/Surface.jl
=> Use more generic methods in Surface.jl

integration_tests/utils/compute_mse.jl
Thanks @trontrytel, for finding this!
=> Fix contour plot time for tc main

integration_tests/utils/mse_tables.jl
Trying to add qr plot to contours and profiles for Rico.
=> add qr plot in Rico

integration_tests/utils/Cases.jl
I took a second stab at #287. I think this one is a clearer win.
Supersedes #287.
=> Refactor Cases.jl

src/closures/buoyancy_gradients.jl
This PR renames the prefactor used in the buoyancy gradient for readability.
=> Rename buoyancy gradient prefactor for readability.

integration_tests/utils/Cases.jl
We actually don't need any of these `PhaseEquil` calls in Cases.jl, because it's already performed in `satadjust` (and overwrites temperature).
Because of the way some profiles are initialized, we couldn't do this with all cases (specifically, TRMM, ARM, GATE, DYCOMS).
=> Further refactor cases--remove unnecessary calls

src/Operators.jl
I wrote this down a while ago but never added it to the docs
=> Add docs to construct_tridiag_diffusion_en

integration_tests/utils/Cases.jl, integration_tests/utils/mse_tables.jl
A minor change that ensures surface flux is being read from the LES file.
=> use fixed surface flux for LES driven case

src/Turbulence_PrognosticTKE.jl, src/turbulence_functions.jl
some calls to wstar and update inversion seem to be unused
=> remove unneeded wstar calls

src/surface_functions.jl
I'm perplexed as to how this managed to merge in the first place (as I'm seeing this error on buildkite).
=> Fix incorrect qualification of method, improve names

integration_tests/utils/Cases.jl, integration_tests/utils/main.jl, src/EDMF_Environment.jl, src/EDMF_Rain.jl, src/EDMF_Updrafts.jl, src/Radiation.jl, src/Surface.jl, src/Turbulence_PrognosticTKE.jl, src/Variables.jl, src/diagnostics.jl, src/dycore_api.jl, src/types.jl, src/update_aux.jl
This PR changes several (grid mean) variables from arrays to ClimaCore Fields.
I apologize if this is disruptive / causes a lot of git conflicts.
=>  Make several grid mean variables fields

integration_tests/utils/main.jl, src/EDMF_Environment.jl, src/EDMF_Precipitation.jl, src/EDMF_Updrafts.jl, src/Turbulence_PrognosticTKE.jl, src/diagnostics.jl, src/io.jl, src/types.jl
The last of the peel offs from #506 Hopefully no changes as well. 🤞
=> Additional data structs for snow

src/Turbulence_PrognosticTKE.jl
Use ClimaCore operators in `get_GMV_CoVar`. It looks like this results in fewer allocations, so hopefully we'll see some micro improvements as we implement these more widely.
=> Use ClimaCore operators in get_GMV_CoVar

src/Turbulence_PrognosticTKE.jl
This PR fixes a bug in w third moment equation by collecting horizontal diffusive (turbulent entrainment) flux from all updrafts
=> fix w third moment bug

integration_tests/utils/generate_namelist.jl, integration_tests/utils/main.jl
This PR makes it possible to skip IO, which should be helpful for performance analysis
=> Add option to skip IO, for perf analysis

src/EDMF_Updrafts.jl, src/Fields.jl, src/Turbulence_PrognosticTKE.jl
This is a peel off PR from #473. This PR adds a few `@inbounds` to some loops, and a performance patch for ClimaCore fields. See [ClimaCore.jl's 275](https://github.com/CliMA/ClimaCore.jl/issues/275)
=> Performance patch

integration_tests/utils/main.jl, src/closures/mixing_length.jl, src/types.jl, src/update_aux.jl
I'm hoping that this will supersede #546.
=> Reduce allocations in MinDisspLen

integration_tests/ARM_SGP.jl, integration_tests/Bomex.jl, integration_tests/DYCOMS_RF01.jl, integration_tests/DryBubble.jl, integration_tests/GABLS.jl, integration_tests/GATE_III.jl, integration_tests/LES_driven_SCM.jl, integration_tests/Nieuwstadt.jl, integration_tests/Rico.jl, integration_tests/SP.jl, integration_tests/Soares.jl, integration_tests/TRMM_LBA.jl, integration_tests/life_cycle_Tan2018.jl, integration_tests/utils/generate_namelist.jl, integration_tests/utils/main.jl, integration_tests/utils/mse_tables.jl, integration_tests/utils/post_run_tests.jl
=> Add post-run tests, error if we do not run to t_max

integration_tests/ARM_SGP.jl, integration_tests/Bomex.jl, integration_tests/DYCOMS_RF01.jl, integration_tests/DryBubble.jl, integration_tests/GABLS.jl, integration_tests/GATE_III.jl, integration_tests/LES_driven_SCM.jl, integration_tests/Nieuwstadt.jl, integration_tests/Rico.jl, integration_tests/SP.jl, integration_tests/Soares.jl, integration_tests/TRMM_LBA.jl, integration_tests/life_cycle_Tan2018.jl
This PR moves the post-run tests inside the experiment tests so that we always see the results of the post-run tests even if the mse tests fail.
=> Sequential tests -> nested tests

integration_tests/utils/generate_namelist.jl, integration_tests/utils/mse_tables.jl
Change vertical resolution in LES_driven_SCM case to improve stability.
=> change LES_driven_SCM default vertical resolution

perf/allocs.jl
This PR adds a second plot to the existing allocation plot. The new one shows the allocations per i-th line so that we can see the distribution of remaining allocations. This PR also prints the full list of allocations (excluding 0-allocating lines).
=> Print full list of allocations, add allocations per line plot

perf/allocs.jl
This should help with seeing the distribution a bit better
=> Add markershape to allocations plot

src/EDMF_Precipitation.jl
fixing a small bug in updating dt_max in the precipitation
=> fix bug in terminal velocity dt_max

src/Turbulence_PrognosticTKE.jl
Unify gridmean covariance expression
=> Unify gm covar expression

integration_tests/utils/main.jl
=> Remove closure, capture sol at tmin/tmax

driver/main.jl, integration_tests/ARM_SGP.jl, integration_tests/Bomex.jl, integration_tests/DYCOMS_RF01.jl, integration_tests/DryBubble.jl, integration_tests/GABLS.jl, integration_tests/GATE_III.jl, integration_tests/LES_driven_SCM.jl, integration_tests/Nieuwstadt.jl, integration_tests/Rico.jl, integration_tests/SP.jl, integration_tests/Soares.jl, integration_tests/TRMM_LBA.jl, integration_tests/life_cycle_Tan2018.jl, test/runtests.jl
It would be nice to time the `solve` method so that, as we reduce allocations, we can get validation from `@time` that allocations are being reduced.
=> Time solve

driver/callbacks.jl, src/Fields.jl
Between this PR and #669 (and fixing up the indefinite integrals), we should be ready to stretch the grid.
=> Make CFL computation based on local dz

diagnostics/compute_diagnostics.jl, driver/callbacks.jl, driver/initial_conditions.jl, src/Turbulence_PrognosticTKE.jl, src/io.jl, src/types.jl
This is a step towards stretched grids. The only things remaining are the two indefinite integrals in radiation for DYCOMS.
=> Use ClimaCore vertical integrals for lwp etc

driver/Cases.jl, driver/main.jl, src/types.jl
Towards removing mutable structs, this PR makes `ForcingBase` immutable.
=> Make ForcingBase immutable

src/types.jl
Wow, this was nice and easy! 🎉
=> Make LESData immutable

driver/callbacks.jl, src/TimeStepping.jl, src/types.jl
=> Make EDMF_PrognosticTKE immutable

driver/Cases.jl, src/Surface.jl, src/Turbulence_PrognosticTKE.jl, src/types.jl
This PR changes some variable names:
- rho_uflux -> ρu_flux
- rho_vflux -> ρv_flux
- rho_hflux -> ρθ_liq_ice_flux
- rho_qtflux -> ρq_tot_flux
=> Improve some names

driver/generate_namelist.jl, src/closures/nondimensional_exchange_functions.jl, src/types.jl
Add linear model for entrainment/detrainment closure, using Relu to ensure positivity.
=> Add linear entrainment closure

src/Turbulence_PrognosticTKE.jl, src/closures/perturbation_pressure.jl, src/update_aux.jl
We're doing pretty good with allocations, but this should reduce a few more
=> Reduce allocations

driver/Radiation.jl, driver/main.jl, src/Grid.jl
This will allow us to make sure that the dycore grid and TC.grid are the same
=> pass mesh from main.jl

driver/generate_namelist.jl, src/closures/entr_detr.jl, src/closures/nondimensional_exchange_functions.jl
This completes #749 by setting up the code for general non local closure
=> restructure for non local entr closure

src/closures/entr_detr.jl
ref: https://github.com/CliMA/TurbulenceConvection.jl/pull/749#discussion_r790055010
=> fix nondim entr detr aux update

driver/Surface.jl, perf/jet.jl, src/Operators.jl, src/update_aux.jl, src/utility_functions.jl
This PR:
- Fixes a type instability in Surface.jl
- adds a jet script
- changes some operations to be in-place
This PR also makes JET a bit happier
=> Add JET script, fix some runtime dispatch

driver/generate_namelist.jl, src/closures/entr_detr.jl, src/closures/nondimensional_exchange_functions.jl, src/types.jl
Just some name changes and added comments for Zongyi from our meeting today as preparations for OperatorFlux
=> prep for FNO, name change and some comments

driver/generate_namelist.jl, driver/parameter_set.jl, src/ClimaParams.jl, src/closures/nondimensional_exchange_functions.jl
This PR merges the working version of FNO entr closure into main.
=> add FNO entr detr function

src/Turbulence_PrognosticTKE.jl
Remove some field allocations.
=> Remove allocation

driver/Cases.jl, driver/Surface.jl, driver/compute_diagnostics.jl, driver/dycore.jl, driver/initial_conditions.jl
Outside of src we should not use 'TC.thermo_state_pθq' but rather directly use 'TD.PhaseEquil_pθq'.
=> call TD.PhaseEquil_pθq outside of src

driver/dycore.jl, src/Turbulence_PrognosticTKE.jl
just a rename, as the function now compute a flux and not a tendency
=> rename compute_sgs_tendencies to compute_sgs_flux

driver/generate_namelist.jl, src/closures/entr_detr.jl, src/closures/nondimensional_exchange_functions.jl, src/types.jl
Make dim scale for entrainment a namelist option, add 1/z scale
=> Make dim scale for entrainment a namelist option, add 1/z scale

driver/main.jl
=> clean a bool from params

driver/compute_diagnostics.jl, driver/dycore.jl, driver/initial_conditions.jl, driver/main.jl, src/EDMF_Precipitation.jl, src/EDMF_Updrafts.jl, src/Turbulence_PrognosticTKE.jl, src/closures/entr_detr.jl, src/closures/perturbation_pressure.jl, src/types.jl, src/update_aux.jl
rename EDMF_PrognosticTKE  to EDMFModel
=> Improve names

post_processing/compute_mse.jl
This PR reverts #797 to reinforce the regression tests.
=> Revert PR 797 to reinforce regression tests

src/EDMF_Environment.jl
=> Fix dry/moist thermo state diagnostics

driver/Cases.jl, driver/dycore.jl, driver/initial_conditions.jl, src/turbulence_functions.jl, src/update_aux.jl, src/variables.jl
move some θ_virt  and Ri to grid mean aux
=> move some vars to aux_gm

.buildkite/pipeline.yml, integration_tests/3dBomex.jl
Similar to #810, this PR adds a 3D box of Bomex, that calls TC.jl (albeit using the wrong space). This may be a simpler stepping stone to get working before moving to the sphere since viz and transformations will be simpler/easier.
=> Add 3d bomex box

src/closures/entr_detr.jl
Add filters to nonlocal entr func, fix c_div bug
=> add filters to nonlocal entr func, fix c_div bug

src/utility_functions.jl
=> Add compare debug function

driver/callbacks.jl, driver/compute_diagnostics.jl, driver/dycore.jl, driver/main.jl, integration_tests/3dBomex.jl, integration_tests/baroclinic_wave.jl, perf/common.jl, src/types.jl
I am not sure how to properly move the definitions of `AbstractPrecipitationModel` out of src, 
@charleskawczynski ?
Otherwise this I think is a start for defining microphysics independently of the EDMF model
=> pass precip_model via simulation1d

driver/generate_namelist.jl, driver/main.jl, driver/parameter_set.jl, src/ClimaParams.jl, src/closures/nondimensional_exchange_functions.jl, src/types.jl
- A simple Random Fourier Feature approximation to a scalar-valued GP with squared exponential kernel and four inverse lengthscales (one for each Pi group input)
- Separates optimizable (expansion coefficients and hyperparameters) from fixed (realizations of random variables) parameters in the namelist
=> Random Feature Entr Detr Local Closure

driver/Cases.jl, driver/dycore.jl
=> Improve logging, remove ref to undefined var

driver/main.jl, test/runtests.jl
Can people test out if this works in general?
=> Convert Namelist arrays to tuples

driver/main.jl
I think this is a more careful way to handle our nc file open/closing. This should ensure that our nc files always close-- which I've been thinking about since looking more at the calibration pipeline / failures.
IIRC, I took this pattern from NCDatasets (looking at how the `do`-block syntax works).
Closes #55
cc @haakon-e
=> Ensure NC files always close

Project.toml, driver/main.jl
=> Include exception error in log for crashed simulations

post_processing/compute_mse.jl
Reverts the critical part of #849.
=> Hook regression tests back in

docs/Manifest.toml, perf/Manifest.toml, test/Manifest.toml
#855 introduced an environment bug-- I forgot to dev the TurbulenceConvection package.
=> Fix environments - dev TC pkg in environments

docs/Manifest.toml, integration_tests/Manifest.toml, perf/Manifest.toml
I did this by running `julia .dev/up_deps.jl`, and undoing the changes to the Project.toml files (I don't think those are supposed to change).
=> Up manifests

driver/generate_namelist.jl, integration_tests/artifact_funcs.jl, post_processing/compute_mse.jl
This is a prep PR to fixing some issues we're having with lazy downloads of artifacts
=> Move artifact functions to separate file

driver/compute_diagnostics.jl, driver/dycore.jl, driver/main.jl, src/Grid.jl, src/dycore_api.jl, src/variables.jl
This PR adds single value per column fields to the `diagnostics` `FieldVector`.
=> Add single value per column fields

docs/Manifest.toml, integration_tests/Manifest.toml, perf/Manifest.toml
Ran `julia .dev/up_deps.jl` for this PR.
=> Up dependencies

Project.toml, docs/Manifest.toml, integration_tests/Manifest.toml, perf/Manifest.toml
I have:
- bumped `TC.jl` version: `0.17.0` -> `0.17.1`
- run `.dev/up_deps.jl` with julia version `1.7.2`
=> +0.0.1 to TC.jl version, update deps to julia 1.7.2

driver/generate_namelist.jl, driver/parameter_set.jl, src/ClimaParams.jl, src/closures/nondimensional_exchange_functions.jl, src/types.jl
Separates weight and bias parameter vectors for easy zeroing of biases and makes neural network architecture a namelist argument.
=> separate weights and biases

.buildkite/pipeline.yml, driver/Cases.jl, integration_tests/driver.jl, post_processing/case_kwargs.jl, post_processing/compute_mse.jl, post_processing/mse_tables.jl, utils/print_new_mse.jl
=> Add truncated GATE to CI

Project.toml, driver/generate_namelist.jl, driver/parameter_set.jl, src/EDMF_Precipitation.jl
This PR adds more parameters for calibration. It requires CLIMAParameters v0.4.3 (the new patch release).
For future reference, the correct workflow to merge this is to: 
1) open a separate PR with up_deps
2) clear the depot for the CI
3) bump version (it's a breaking change since now we are only compatible with the new version of CP.jl)
4) merge
5) tag a new release.
=> add more parameters for calibration

driver/Cases.jl, driver/dycore.jl, src/variables.jl
This peels off a small working piece from #937.
=> Add thermo state fields, use in one place

integration_tests/download_artifacts.jl, perf/alloc_per_case.jl, perf/alloc_per_case_with_init_io.jl, perf/common.jl, post_processing/compute_mse.jl, src/TurbulenceConvection.jl, utils/move_output.jl
=> Add backticks to info statements

integration_tests/driver.jl
=> Warn when overwriting namelist

.dev/Project.toml, driver/main.jl, integration_tests/3dBomex.jl, integration_tests/baroclinic_wave.jl, perf/allocs.jl, src/EDMF_Updrafts.jl, src/closures/nondimensional_exchange_functions.jl, src/variables.jl
We need to upgrade to the latest JuliaFormatter (see [this issue](https://github.com/domluna/JuliaFormatter.jl/issues/575)).
=> Upgrade to latest JuliaFormatter

docs/Manifest.toml, integration_tests/Manifest.toml, perf/Manifest.toml
=> Upgrade deps

driver/dycore.jl, src/Fields.jl, src/TurbulenceConvection.jl
This works, but we'll need to remove
```julia
Base.:-(a::FT, b::CCG.Covariant3Vector{FT}) where {FT} = a .- b.u₃
Base.:+(a::FT, b::CCG.Covariant3Vector{FT}) where {FT} = a .+ b.u₃
```
And appropriately apply changes.
=> Use Covariant3Vector for grid-mean w

driver/generate_namelist.jl, src/closures/entr_detr.jl, src/types.jl
Allow for different dimensional scales in entrainment/detrainment closure.
=> Allow different dimensional scales for entr/detr

driver/compute_diagnostics.jl, src/variables.jl
A draft on how to compute precipitation flux diagnostics. I want it defined on cell faces, so that we can easily get the value at the surface.
=> draft of precipitation flux output

driver/Cases.jl
This is one of the only places in the code where we broadcast over `parent(field) .= array`, which is problematic when we go to a sphere.
=> Refactor init profiles in LES driven SCM

driver/NetCDFIO.jl, driver/main.jl, integration_tests/cli_options.jl, integration_tests/driver.jl, src/Fields.jl, src/Grid.jl, src/types.jl
This is a peel off PR from #1074.
=> Prep for sphere

driver/callbacks.jl, driver/dycore.jl, driver/main.jl, perf/common.jl, perf/jet.jl
This is a peel off from #1074.
=> Compute column grid on the fly from state space

driver/main.jl, perf/common.jl, perf/jet.jl
Another peel off PR from #1074.
=> Remove state from Simulation1D

driver/Cases.jl, driver/Forcing.jl, driver/Radiation.jl
This is hopefully the last peel off PR from #1074.
=> Generalize some driver init and forcing for LES driven SCM

.buildkite/pipeline.yml, driver/callbacks.jl, driver/main.jl, integration_tests/driver.jl, integration_tests/sphere_utils.jl, perf/inference_flame.jl, perf/invalidations.jl, perf/pgd.jl, src/Fields.jl, src/Grid.jl, src/types.jl, test/runtests.jl
This PR
- Adds an edmf sphere test with 24 columns
- Adds (broken) tests to ensure that there's no horizontal variation for spherical cases
This will allow us to incrementally fix our application of metric terms in TC (and its host dycore).
=> Add test edmf sphere test

driver/Cases.jl, driver/NetCDFIO.jl, driver/main.jl, perf/precompilable_no_init.jl, src/EDMF_Environment.jl, src/closures/buoyancy_gradients.jl, src/closures/nondimensional_exchange_functions.jl, src/types.jl, src/update_aux.jl
=> Fix some type instabilities

driver/Surface.jl
=> Fix more type instabilities

driver/parameter_set.jl, src/EDMF_functions.jl, src/TurbulenceConvectionParameters.jl, src/types.jl
=> Move experimental parameters to struct

driver/parameter_set.jl, src/TurbulenceConvectionParameters.jl, src/closures/nondimensional_exchange_functions.jl, src/types.jl
=> Move experimental params into struct

driver/parameter_set.jl, src/TurbulenceConvectionParameters.jl, src/closures/nondimensional_exchange_functions.jl, src/types.jl
=> Move more parameters to structs

driver/parameter_set.jl, src/TurbulenceConvectionParameters.jl, src/closures/nondimensional_exchange_functions.jl, src/types.jl
=> Move more parameters to edmf struct

driver/parameter_set.jl, src/EDMF_functions.jl, src/TurbulenceConvectionParameters.jl, src/closures/entr_detr.jl, src/closures/nondimensional_exchange_functions.jl, src/types.jl
=> Remove unused parameter, move params to structs

driver/main.jl, src/types.jl
This PR adds printing of a summary for the edmf model.
This already helped me catch a bug.
=> Add printing of edmf model summary

driver/compute_diagnostics.jl, driver/main.jl, driver/parameter_set.jl, src/EDMF_functions.jl, src/TurbulenceConvectionParameters.jl, src/closures/entr_detr.jl, src/closures/nondimensional_exchange_functions.jl, src/closures/perturbation_pressure.jl, src/types.jl
=> Move more parameters into structs

driver/Cases.jl, driver/Forcing.jl, driver/dycore.jl, driver/initial_conditions.jl, driver/main.jl, src/types.jl
This PR alleviates our dependence on CasesBase
=> Alleviate dependence on CasesBase

driver/Cases.jl, src/EDMF_Updrafts.jl, src/microphysics_coupling.jl
Missed some calls in #1154. I think that this is all of them.
=> Add missed calls to thermo wrappers

driver/parameter_set.jl, src/EDMF_Precipitation.jl, src/TurbulenceConvection.jl, src/microphysics_coupling.jl, src/update_aux.jl
=> Add microphysics param wrappers

driver/Surface.jl, driver/parameter_set.jl, src/TurbulenceConvection.jl
This PR adds surface fluxes parameter wrappers. This builds ontop of #1154.
=> Add / use surface fluxes parameters wrapper

README.md, docs/bibliography.bib, src/name_aliases.jl
- Reflect actual status of He et al reference.
- Add more name_aliases to keep in sync with that theta branch.
=> Remove submitted status of He et al, add more name_aliases.

docs/src/PlotReferenceStates.jl
Fix the reference state plots, right now only pressure is shown
=> Fix ref state plots

src/closures/nondimensional_exchange_functions.jl
I suggest using ReLu in RF entrainment to unify formulation with the other models
=> use relu in RF output

driver/compute_diagnostics.jl
Add notice about vertical integrals using ClimaCore Field sum.
Closes #1224 .
=> Add notice about vertical integrals using ClimaCore Field sum.

driver/callbacks.jl, driver/compute_diagnostics.jl, driver/dycore.jl, driver/main.jl
Adds diagnostics for two quantities of interest/metrics of the EDMF scheme: the integrated vertical subgrid-scale fluxes of moisture and entropy. 
- Easy analysis of EDMF response to global warming.
- Enables comprehensible scalar-based loss functions for calibration.
=> Add integrated vertical SGS flux diagnostics.

Project.toml
Additions since 0.27.6:
- Updates output of RF NN closure to ReLu,
- Adds a few integrated metrics to the package.
=> Update theta-var to 0.27.7

driver/dycore.jl, integration_tests/cli_options.jl, src/EDMF_Environment.jl
This PR fixes a bug in the non-equilibrium moisture model where we were not applying the environment cloud condensate source/sink terms to the grid mean equation.
Will fix the non-equilibrium model
(Provide references to any link issues. Use closes #issuenum to automatically close an open issue)
- Closes #1231
=> Bugfix in non-equilibrium moisture model

perf/flame.jl
This PR
- Updates the flame graph by putting the work inside a function and removing the global-scope loop, which seems to pollute the flame graph results a bit
- Increases the samples to 1000 to give higher resolution output
=> Update flame script

docs/Manifest.toml, integration_tests/Manifest.toml, perf/Manifest.toml
I'm updating dependecies to get CLIMAParameters v0.6.4
=> updte deps for CLIMAParametes 0.6.4

driver/parameter_set.jl
I need to add 4 more parameters to our namelist parsing. I need them for the calibration experiments done with my SURFs using the CEDMF pipeline
=> add KK2000 autoconversion params

Project.toml
=> Version 1.0.0 release

.dev/resolve_deps.jl
Would that be the script to resolve deps instead of updating?
=> add resolve script

test/Project.toml, test/runtests.jl
=> Add Aqua tests

.dev/Project.toml, .dev/rm_add_up_deps.jl
This PR adds a script, similar to `up_deps.jl`, which automatically adds / removes a specified package (and version) to avoid needing to update package versions.
=> Add pkg manager script

src/utility_functions.jl
Takes out one of the LESdrivenSCM cases that has a corrupted LES stats files. This results in TC breaking consistently when trying to run the case.
=> Take out LESdrivenSCMwith corrupted LES output.

driver/generate_namelist.jl, post_processing/mse_tables.jl
fixes bugs introduced in #1251 and #34
=> fix: LES_driven_SCM & DryBubble default namelist

Project.toml
Update with new developments/fixes for calibration.
=> Update to v1.1

Project.toml
=> Bump to version 1.2.0

src/types.jl
- Remove duplicate entrainment structs and eliminate compilation warnings.
=> Remove duplicate structs

Project.toml
=> Bump to v1.3

Project.toml, docs/Manifest.toml, integration_tests/Manifest.toml, integration_tests/Project.toml, integration_tests/artifact_funcs.jl, perf/Manifest.toml
Updates ArtifactWrappers after breaking changes, which allows updating the same package in CalibrateEDMF.jl.
=> Update ArtifactWrappers, depependencies

src/EDMF_functions.jl, src/update_aux.jl, src/variables.jl
=> Cache k-hat

.dev/Project.toml, .dev/rm_add_up_deps.jl, .dev/up_deps.jl, docs/Manifest.toml, integration_tests/Manifest.toml, perf/Manifest.toml, perf/allocs.jl
This PR
- Updates the `up_deps.jl` script
- Updates the JuliaFormatter to version 1
- Updates the dependencies
- Applies the formatter
=> Update `up_deps.jl`, upgrade JuliaFormatter, update deps

driver/compute_diagnostics.jl, src/variables.jl
This PR adds some variables to the cache. Peel off of #1306.
=> Cache some area fraction variables

src/EDMF_functions.jl, src/update_aux.jl, src/variables.jl
This peels off parts from #1306.
=> Add some variables to cache

driver/callbacks.jl
This PR fixes some type instabilities / allocations by adding a function barrier and adding type annotations
=> Add function barrier to fix type instability

driver/generate_namelist.jl, src/closures/nondimensional_exchange_functions.jl, src/types.jl
=> add nn helper funcs and linear no-bias option

driver/generate_namelist.jl, src/closures/entr_detr.jl, src/types.jl
Add inverse atmospheric scale height as entrainment dimensional scale option.
=> Add inv scale height as entrainment dimensional scale option

Project.toml
Bump version for patch release
=> bump patch version 1.3.4

driver/Cases.jl, driver/main.jl
change les_data_kwarg to aux_data_kwarg so that we have a better name for use in socrates
=> change les_data_kwarg to aux_data_kwarg

driver/compute_diagnostics.jl, src/EDMF_functions.jl, src/diagnostics.jl
Fix bottom boundary condition on diffusive fluxes
=> Fix bottom boundary condition on diffusive fluxes

.github/workflows/CodeCov.yml, .github/workflows/JuliaFormatter.yml, .github/workflows/UpDeps.yml, .github/workflows/ci.yml, .github/workflows/docs.yml, README.md, bors.toml
Remove bors, trigger CI with github
=> Remove bors, trigger CI with github

.github/workflows/docs.yml
Modify CI to ensure Docs are built for main branch only.
=> Modify CI for docs

Project.toml, docs/Manifest.toml, integration_tests/Manifest.toml, perf/Manifest.toml
=> bump patch version

src/closures/nondimensional_exchange_functions.jl
Change activation function to relu in NN entr closure
=> Change activation function to relu in NN entr closure

src/EDMF_functions.jl, src/closures/entr_detr.jl
Maybe this is all that's needed?
cc @costachris , @haakon-e
=> Hoist aux_up in compute_updraft_top

src/EDMF_functions.jl
Extrapolate bottom bc in tke transport term
=> Extrapolate bottom bc in tke transport term
