integration_tests/ARM_SGP.jl
integration_tests/Bomex.jl
integration_tests/DYCOMS_RF01.jl
integration_tests/Rico.jl
integration_tests/Soares.jl
integration_tests/TRMM_LBA.jl
integration_tests/utils/compute_mse.jl
src/EDMF_Updrafts.jl

Turned out this was the last missing piece. What I thought was a bug fix, I overlooked that `ql` and `h` are _decremented_, and simply needed initial values (they're not initialized in SCAMPy). I don't understand exactly how this works, and why we want it that way, but I'll leave those changes / improvements for a later PR.
DYCOMS now appears nearly identical with SCAMPy master (commit `496dad0c2438235684823511cacbf5761d6a237c`) 🎉

Fix buoy calc bug. Dycoms now match scampy

---

src/Turbulence_PrognosticTKE.jl

#25 exercises the case where `alen` is equal to the length of `avals`. As this is an offset array, the proper translation was to use `xrange`, which effectively means indexing with `0:alen-1`.

Fix nh pressure index, as this is indexing into OffsetArray

---

integration_tests/ARM_SGP.jl
integration_tests/Bomex.jl
integration_tests/DYCOMS_RF01.jl
integration_tests/Rico.jl
integration_tests/Soares.jl
integration_tests/TRMM_LBA.jl
src/Turbulence.jl
src/TurbulenceConvection.jl
src/Turbulence_PrognosticTKE.jl
src/turbulence_functions.jl

Replace tdma with built-in Julia implementation

---

integration_tests/utils/main.jl
src/NetCDFIO.jl

Store namelist and paramlist in output folder together with the NetCDF datafile.

fix: write namelist and paramlist to file

---

src/Turbulence_PrognosticTKE.jl
src/types.jl

It'd be nice to use `grid` and `ref_state` for local variables. hopefully `grid` will be available everywhere at some point, so `get_grid` may be temporary.

Change grid,ref_state to get_grid,reference_state

---

Project.toml
docs/Project.toml
docs/src/ReferenceStates.md
integration_tests/utils/main.jl
integration_tests/utils/parameter_set.jl
src/ReferenceState.jl
src/Turbulence.jl
src/types.jl

This peels off non-behavior changes from #25:
- Dependence of CLIMAParameters added
- Parameter sets become available in many functions
- Parameter sets are read from the namelist file
Note that parameter sets become available, but are not yet used.

Add climaparameters dep

---

docs/src/ReferenceStates.md
integration_tests/ARM_SGP.jl
integration_tests/Bomex.jl
integration_tests/DYCOMS_RF01.jl
integration_tests/DryBubble.jl
integration_tests/GABLS.jl
integration_tests/GATE_III.jl
integration_tests/Nieuwstadt.jl
integration_tests/Rico.jl
integration_tests/SP.jl
integration_tests/Soares.jl
integration_tests/TRMM_LBA.jl
integration_tests/life_cycle_Tan2018.jl
integration_tests/utils/generate_namelist.jl
test/perf.jl
test/profile.jl

I accidentally forgot to use case-sensitive replace-all in #34. This PR changes the namelist module to be TitleCase

Make NameList module TitleCase

---

integration_tests/utils/compute_mse.jl

This PR
- Improves the log in `compute_mse`
- imports plots to avoid name conflicts
- Matches the contour levels in contour plots
- Combines contour plots into single plot
Closes #14

Match tc-scampy contour levels

---

integration_tests/utils/generate_namelist.jl

without this fix running:
julia --project integration_tests/utils/generate_namelist.jl Soares
julia --project integration_tests/utils/main.jl Soares
breaks with:
"""""
ERROR: LoadError: KeyError: key "uuid" not found
Stacktrace:
[1] getindex(h::Dict{String, Any}, key::String)
@ Base ./dict.jl:482
[2] TurbulenceConvection.NetCDFIO_Stats(namelist::Dict{String, Any}, Gr::TurbulenceConvection.Grid{OffsetArrays.OffsetVector{Float64, Vector{Float64}}, Float64})
@ TurbulenceConvection ~/Documents/codes/TurbulenceConvection.jl/src/NetCDFIO.jl:29
[3] Simulation1d(namelist::Dict{String, Any})
@ Main ~/Documents/codes/TurbulenceConvection.jl/integration_tests/utils/main.jl:27
[4] main1d(namelist::Dict{String, Any}; time_run::Bool)
@ Main ~/Documents/codes/TurbulenceConvection.jl/integration_tests/uti …

add correction to run without tests

---

src/EDMF_Environment.jl
src/EDMF_Updrafts.jl
src/microphysics_functions.jl
src/parameters.jl
src/types.jl

This is one step towards moving the microphysics parameters to the namelist, so that we can use the calibration pipeline for those parameters. I have confirmed the results using the rain_model = 'cutoff' are the same after this change. @trontrytel @charleskawczynski Could you please take a look and let me know whether it makes sense? Thanks!

move max_supersaturation to namelist

---

src/Forcing.jl
src/ReferenceState.jl
src/Turbulence_PrognosticTKE.jl
src/microphysics_functions.jl
src/turbulence_functions.jl

Remove unused functions, fix some typos. I don't think these extra functions are needed, but it would be nice to get confirmation.

Remove unused functions

---

src/Turbulence_PrognosticTKE.jl
src/Variables.jl
src/types.jl

- Use more grid abstractions
- Delete useless code
- Add type constraints

Use more grid abstractions

---

integration_tests/ARM_SGP.jl
integration_tests/TRMM_LBA.jl
src/python_primitives.jl

This PR changes `pyinterp` to use linear interpolation, which is what `numpy.interp` does by default.
I believe TRMM should match with SCAMPy far better with these changes. This should hopefully give us a clearer view of how #43 changes the results.

Match scampy by using linear interpolation

---

integration_tests/utils/compute_mse.jl

The previous Nieuwstadt link pointed to the PYCLES link (which had the same exact URL). cc @yairchn

Fix scampy Nieuwstadt artifact file link

---

integration_tests/utils/compute_mse.jl

It's a bit difficult to see all plots when they're right on top of each other, and therefore difficult to know if the TC.jl solution is very good or NaNs (NaNs solutions do not show up). This PR swaps the order so that TC is last so that it's always clear. I think that not seeing the artifact file solutions (behind the TC.jl solution) is okay since they don't change and are never NaNs.

Swap plots so that TC.jl is last

---

integration_tests/TRMM_LBA.jl
src/ReferenceState.jl

This is likely not what we want in the end, but for early-on comparisons, and perhaps if there are assumptions elsewhere about how the ref state bcs are applied, this PR fixes a translation bug in the ref state bcs: in SCAMPy, the `p_half` field has two missing elements at the start and end of the array, and _both_ points are _mirrored_ in _log-space_ about the boundary. This enters the computations [here](https://github.com/CliMA/TurbulenceConvection.jl/blob/main/src/Turbulence_PrognosticTKE.jl#L511).

Fix translation bug in ref state bcs

---

src/NetCDFIO.jl

Sometimes julia complains that I don't have permission to create the nc file (sometimes when simulations crash). This should smooth the workflow a bit.

Remove nc file if it exists before creating it

---

.github/codecov.yml

Codecov comments in the files changed is really noisy and gets in the way of code review. Let's turn off the codecov comments it.

Turn off codecov comments

---

integration_tests/utils/parameter_set.jl
src/TurbulenceConvection.jl
src/microphysics_functions.jl
src/types.jl

This should behave the same as before (and, in fact, `conv_q_vap_to_q_liq` is not yet used).

Move τ_cond_evap to clima params method call

---

integration_tests/ARM_SGP.jl
integration_tests/Bomex.jl
integration_tests/DYCOMS_RF01.jl
integration_tests/Nieuwstadt.jl
integration_tests/Rico.jl
integration_tests/Soares.jl
integration_tests/TRMM_LBA.jl
src/Operators.jl
src/Turbulence_PrognosticTKE.jl

This should help us move towards removing ghost points.

Use bcs and avoid accessing ghost points

---

src/Turbulence_PrognosticTKE.jl
src/Variables.jl
src/turbulence_functions.jl

This PR removes more calls to python primitives (xrange), and uses the field constructors.

Use more grid and field abstractions

---

.gitignore
integration_tests/utils/Artifacts.toml

This artifact file has proven to be problematic for people's workflow. I think everything should work fine if we git-ignore it.

Ignore artifact file to avoid git conflicts

---

integration_tests/DYCOMS_RF01.jl
src/Radiation.jl

This PR:
- Makes `f_rad` a `face_field` (with the now correct size)
- Removes a call to `revxrange`, which we need to phase out
- Uses OrdinaryDiffEq to integrate the radiation profile, instead of doing it ourselves
- Fixes the upper radiation BC, which didn't seem to match the literature:

Fix and improve dycoms radiation

---

src/EDMF_Rain.jl
src/python_primitives.jl

I think that this is done correctly, note that we're not traversing the `term_vel[k] = terminal_velocity(Rain.C_drag, Rain.MP_n_0, QR.values[k], self.Ref.rho0_half[k])` in reverse order, since I don't think that should have any impact on the result.

Remove `revxrange`

---

integration_tests/utils/Cases.jl
src/EDMF_Environment.jl
src/EDMF_Updrafts.jl
src/Grid.jl
src/ReferenceState.jl
src/TurbulenceConvection.jl
src/Turbulence_PrognosticTKE.jl
src/Variables.jl
src/python_primitives.jl
src/turbulence_functions.jl

This is work that I started this morning, just wanted to push it up to see if/how things run.

Convert to 1-based indexing

---

integration_tests/utils/Cases.jl
src/EDMF_Environment.jl
src/EDMF_Updrafts.jl
src/Turbulence_PrognosticTKE.jl
src/Variables.jl
src/types.jl

Closes #59. Note that this may actually be behavior-changing if H and THL are ever out of sync.

Remove THL, and replace with H

---

integration_tests/ARM_SGP.jl
integration_tests/Bomex.jl
integration_tests/DYCOMS_RF01.jl
integration_tests/Nieuwstadt.jl
integration_tests/Rico.jl
integration_tests/Soares.jl
integration_tests/TRMM_LBA.jl
src/Turbulence_PrognosticTKE.jl
src/types.jl

This PR consolidate turbulent entrainment to a single term that is effectively added to the dynamic entrainment. It is a step on the way to merging the two into a single closure file. 
** this branch has behavioral changes as it computes turbulent entrainment only at half levels and interpolates it to full levels **

Consolidate turbulent entrainment

---

.github/workflows/ci.yml
bors.toml

For some reason, the 1.5 CI, which doesn't even run any tests, is taking even longer than the entire buildkite run. Let's

Remove 1.5 CI

---

src/EDMF_Updrafts.jl

First step to handle the definition of h and qt in extra buoyancy part in the updrafts

set qt and h in extrap buoyancy to clear values

---

integration_tests/ARM_SGP.jl
integration_tests/Bomex.jl
integration_tests/DYCOMS_RF01.jl
integration_tests/DryBubble.jl
integration_tests/GABLS.jl
integration_tests/Nieuwstadt.jl
integration_tests/Rico.jl
integration_tests/SP.jl
integration_tests/Soares.jl
integration_tests/TRMM_LBA.jl
integration_tests/life_cycle_Tan2018.jl
integration_tests/utils/compute_mse.jl

Big improvement on #3, here. This PR makes LES data optional, so this PR adds regression tests for
- DryBubble
- life_cycle_Tan2018
- SP
And compares against SCAMPy

Make les comparison optional, + more cases plots

---

integration_tests/utils/compute_mse.jl

This PR fixes some paths that were not set up correctly in #110.

Fix tc main results path

---

src/Turbulence_PrognosticTKE.jl

This PR makes the EDMF more resilient to different parameter values by preventing negative qt in the updraft.

Make sure that qt in updraft is non negative 

---

integration_tests/utils/compute_mse.jl

This PR updates the layout of the profile plots to squeeze out the lost white space. I also changed the layout to be 5 columns (it was previously 4). We can change it back if people prefer 4, most of the gained space was in the horizontal direction, so I think this actually preserves the look of the figures over sticking with 4, but I have no strong feelings about this.
Closes #124.

Squeeze out space in profile plots

---

integration_tests/GABLS.jl
integration_tests/TRMM_LBA.jl
src/EDMF_Rain.jl
src/Turbulence_PrognosticTKE.jl

This PR unifies the time steps in the model across the updrafts and the grid mean the environment and the microphysics. The tilmestep is set to 3 sec which works. Next step would be to add a CFL condition that combines updraft velocity and rainfall velocity to get the optimal tilmestep. 
** behavioral changes !! ** 
take a close look

unify timesteps in the model

---

.buildkite/pipeline.yml
integration_tests/ARM_SGP.jl
integration_tests/Bomex.jl
integration_tests/DYCOMS_RF01.jl
integration_tests/DryBubble.jl
integration_tests/GABLS.jl
integration_tests/Nieuwstadt.jl
integration_tests/Rico.jl
integration_tests/SP.jl
integration_tests/Soares.jl
integration_tests/TRMM_LBA.jl
integration_tests/life_cycle_Tan2018.jl
integration_tests/utils/compute_mse.jl
integration_tests/utils/mse_tables.jl
utils/print_new_mse.jl

This PR should be a nice quality of life improvement for updating the MSE tables.
Previously, we had to click into each tab (for each case) and copy the table to the corresponding file
With this PR: a new job prints the entire mse table file contents after all cases are complete--so we only need to copy these file contents into the single mse tables file.

Merge mse tables->1 file, print mse table post run

---

integration_tests/utils/parameter_set.jl
src/Turbulence_PrognosticTKE.jl
src/closures/perturbation_pressure.jl
src/types.jl

Moving only pressure related parameters to parameter_set.jl

move pressure parameters to param_set

---

integration_tests/utils/mse_tables.jl
utils/print_new_mse.jl

This PR should make the mse tables slightly easier to copy-paste-- we'll no longer need to trim the trailing spaces.

Make mse tables easier to copy-paste

---

src/Operators.jl
src/Turbulence_PrognosticTKE.jl
src/utility_functions.jl

This PR:
- Makes one of the advection operators use bcs
- Changes the index from `k+1` to `k` in the call to `upwind_advection_area`. Doing so requires changing the indices inside the method, and I noticed something odd: we are (and have been for a while) dividing `∇m` by `ρ0_half[k + 1]`.

Make advection operators use bcs, fix index in method call

---

src/Turbulence_PrognosticTKE.jl

This PR:
- Skips traversing ghost points in covariance equations
- Uses unicode in covariance equation functions
🤞🏻 that these ghost points are not used anywhere!

Skip traversing ghost points in covar equations

---

src/Forcing.jl
src/Operators.jl
src/Turbulence_PrognosticTKE.jl

This PR:
- Renames ccut_onesided -> ccut_downwind and same with ∇
- Adds an upwind operator, removes the use of interp2pt in Operators.jl

Add upwind operator, remove use of interp2pt in Operators

---

.github/codecov.yml

Found this [here](https://docs.codecov.com/docs/github-checks#disabling-github-checks-patch-annotations-via-yaml).

Silence codecov annotations

---

src/Forcing.jl
src/Radiation.jl
src/Turbulence_PrognosticTKE.jl
src/Variables.jl
src/types.jl

Looking through the code, I realized that _all_ grid mean quantities seem to be updated in a standardized way, and I think we can fuse all the tendencies into a single loop.
This is still not a great final version, but we can start thinking about how we want to dispatch to add sources for a given model.

Fuse grid mean tendencies into single loop

---

src/EDMF_Updrafts.jl
src/Turbulence_PrognosticTKE.jl

There's no reason for diagnostic quantities to have `new`, `old`, `tendencies` etc.. This PR removes the use of `new` for diagnostic variables `QL` and `T`. I'm hoping that in a later PR we can make all diagnostic variables fields, rather than, e.g., `UpdraftVariable`.

Remove  diagnostic variables

---

utils/print_new_mse.jl

This PR changes the mse summary to use percentage reduction (i.e., the right-most column of the MSE tables, compared against main) instead of raw mse differences.

Use percentage change in mse summary

---

src/EDMF_Updrafts.jl

~Looking at this part in the code that I found a bit confusing, I realized that the `elseif` block seems to be valid at a single (special) point above which the updraft area fraction is non-zero, then the `else` block handles _every_ point after that. This PR tries to simply remove this logic--since we're updating buoyancy there based on neighboring data.~
Let's just avoid out of bounds indexing in these computations for now..

Avoid OOB (without ghost points) in buoyancy computation

---

docs/src/index.md
src/Operators.jl
src/Turbulence_PrognosticTKE.jl

This PR:
- Adds some docs to the operators, and changes the names to hopefully clarify how they're used
- Adds, what I think was a missing operator, `fcut_upwind`, and uses in place of `dual_faces`.

Add an operator, and docs

---

src/Turbulence_PrognosticTKE.jl
src/turbulence_functions.jl
src/types.jl

This PR restructures the code to split tendency computations from the solve by adding some data structures to `EDMF_PrognosticTKE`.
A step towards #270.

Restructure-- split tendencies from solve

---

integration_tests/utils/Cases.jl
src/EDMF_Environment.jl
src/EDMF_Updrafts.jl
src/TurbulenceConvection.jl
src/Turbulence_PrognosticTKE.jl
src/Variables.jl
src/thermodynamic_functions.jl
src/turbulence_functions.jl
src/types.jl

This PR does several things to smooth the transition to new thermo functions:
- puts all of `thermodynamic_functions.jl` into a submodule, `TCThermodynamics`
- Moves `buoyancy_c` out into `turbulence_functions`, since this function will remain after new thermo functions land
- Adds some methods defined in `thermodynamic_functions.jl` that match Thermodynamic interfaces
- Changes the argument order of `eos` to match the thermodynamics interface

Put eos into a submodule

---

src/thermodynamic_functions.jl

I know that `eos_struct` is only temporary, but this ensures that we're not (and won't) do anything we shouldn't with `eos_struct`.

Make eos_struct immutable

---

integration_tests/utils/main.jl
src/Fields.jl
src/Grid.jl
test/Project.toml

This PR adds ClimaCore fields to the `Simulation1d` struct, which was also made to be immutable. The idea is that we can pass these fields around (in many places in the code), and we will incrementally port over all of the fields from
- GMV
- EDMF_PrognosticTKE
- RadiationBase
- ForcingBase
- EnvironmentThermodynamics
- EnvironmentVariables
etc.
The result is that all of these existing structs will either disappear (🤞🏻) or become much more compact, and potentially immutable.

Add field data structures

---

src/EDMF_Updrafts.jl
src/Turbulence_PrognosticTKE.jl
src/types.jl

ever since we unified the time steps in the model old was effectively equal to values. 
It can be removed, along with 'set_old_with_values' function and relevant type definitions.

remove old

---

docs/src/PlotReferenceStates.jl
integration_tests/utils/Cases.jl
integration_tests/utils/compute_mse.jl
integration_tests/utils/main.jl
src/Fields.jl
src/NetCDFIO.jl
src/ReferenceState.jl
src/TurbulenceConvection.jl
src/diagnostics.jl
src/dycore_api.jl
src/name_aliases.jl

This PR
- Adds io for fields
- Debugs compute mse for plotting steady state data
- Makes `initialize_profiles` accept the cell center reference state
Note that, with these changes, we're no longer relying on
```julia
add_reference_profile(Stats, "alpha0")
write_reference_profile(Stats, "alpha0", alpha0)
add_reference_profile(Stats, "alpha0_half")
write_reference_profile(Stats, "alpha0_half", alpha0_half)
add_reference_profile(Stats, "p0")
write_reference_profile(Stats, "p0", p0)
add_reference_profile(Stats, "p0_half")
write_reference_profile(Stats, "p0_half", p0_half)
add_reference_profile(Stats, "rho0")
write_reference_profile(Stats, "rho0", rho0)
add_reference_profile(Stats, "rho0_half")
write_reference_profile(Stats, "rho0_half", rho0_half)
```
For exporting reference state profiles to …

Use fields for reference state, add field io, compute_mse bugfixes

---

src/EDMF_Environment.jl
src/EDMF_Updrafts.jl
src/Turbulence_PrognosticTKE.jl

In efforts to reduce the many function calls and references to copies of data structures in different places (UpdraftVariables has it's own grid and reference state, same with EnvironmentVariables, ThermodynamicVariables etc.), this PR combines several references, and passes several unpacked data structures from a centralized place. This also reduces the number of aliases and packing/unpacking statements. We also remove some unnecessary function calls
- `PhaseEquil_pθq` was called multiple times in the same loop
- `set_means` was called immediately after `initialize`/ `initialize_DryBubble`, and then called again at the beginning of `update`
In addition, this PR refactors the buoyancy computations so that we maintain the `extrapolate_buoyancy` flag, but reduce the scope of the required …

Add update_aux to prep fusing more ops

---

integration_tests/utils/main.jl
src/Variables.jl
src/diagnostics.jl

I realized that, in addition to exporting auxiliary fields, we should have separate diagnostic fields that are computed only when needed. This PR adds a diagnostics dict so that we can separate these.
This PR also removes a duplicate call to `PhaseEquil_pθq`.

Add diagnostics dict for io

---

src/EDMF_Environment.jl
src/EDMF_Rain.jl
src/EDMF_Updrafts.jl
src/Turbulence_PrognosticTKE.jl

I'm starting to wonder if #73 is the way to go. There's really so many names that need to be re-thought. In addition, it no longer really makes sense to use `self` as a name--since we're using multiple dispatch. This PR makes a few name changes, including
- GMV -> gm
- EnvVar -> en
- EnvThermo -> en_thermo
- UpdThermo -> up_thermo
- UpdVar -> up
- tptke -> edmf
- self -> appropriate names listed above
- Rain -> rain
This doesn't actually change any struct field names, which would be a bit more strict, but I'm wondering what people think about migrating names a bit more incrementally.
cc @trontrytel, @yairchn, @ilopezgp, @haakon-e, @costachris

Rename some variable names

---

src/EDMF_Updrafts.jl
src/Turbulence_PrognosticTKE.jl

This PR is the start of removing updraft "new" variables.
I think that this, and formalizing the solve, is the last remaining hurdle to using OrdinaryDiffEq for timestepping.

Inline set_values_with_new, rm set_new_with_values

---

integration_tests/utils/main.jl
src/EDMF_Environment.jl
src/EDMF_Rain.jl
src/EDMF_Updrafts.jl
src/Turbulence_PrognosticTKE.jl
src/diagnostics.jl
src/dycore_api.jl
src/types.jl

This PR
- Makes prognostic rain a ClimaCore field
- Removes `RainVariable`
- Removes `VariableDiagnostic` (missed in a previous PR)
cc @trontrytel

Make prognostic rain a ClimaCore field

---

integration_tests/utils/Cases.jl
integration_tests/utils/mse_tables.jl

This PR removes the small amounts of surface `qt` that were present in the definition of the GABLS case. The simulation definition in Beare et al (2006) does not have any water, we had this small amount because SCAMPy was incapable of creating profiles for vanishing qt at the surface.

Remove unnecessary water in GABLS

---

docs/src/PlotReferenceStates.jl
integration_tests/ARM_SGP.jl
integration_tests/Bomex.jl
integration_tests/DYCOMS_RF01.jl
integration_tests/DryBubble.jl
integration_tests/GABLS.jl
integration_tests/GATE_III.jl
integration_tests/LES_driven_SCM.jl
integration_tests/Nieuwstadt.jl
integration_tests/Rico.jl
integration_tests/SP.jl
integration_tests/Soares.jl
integration_tests/TRMM_LBA.jl
integration_tests/life_cycle_Tan2018.jl
integration_tests/utils/compute_mse.jl
test/perf.jl
test/profile.jl
test/runtests.jl

Qualifying NameList allows us to modify the namelist in interactive sessions. Which dataset has missing data per variable is now included in the error message.

Qualify NameList methods, improve plotting warnings

---

integration_tests/utils/compute_mse.jl

This is getting peeled off from #423. This PR changes the way that we determine whether we should use cell face vs cell center coordinates by examining the `NCDatasets.dimnames`. I'm not sure that this is part of their public API, but it'll only be used in one place at the moment, and the information is likely to exist somewhere in the NC file.
We can't get rid of `is_face_field` yet because it's still used for determining the coordinates for ordinary Array-backed variables.

Use NC.dimnames to determine face/center

---

integration_tests/utils/main.jl

When running with `dt` < 1s we generate no output. This is because our output is decided based on:
`if mod(sim.TS.t, sim.Stats.frequency) == 0
`
which  runs into rounding errors when the arguments are not integers. Seems like the namelist key is labelled frequency, but we use it in the code more like output interval. 
We could instead start using it like this (i.e. more like a frequency - "every how many steps we should do output)". This way we would avoid floating point issues:
`if mod(iter, sim.Stats.frequency) == 0
`
If we want to keep the current output specification, some ugly workaround solution could look like this:
`if (sim.TS.t - sim.Stats.frequency * div(sim.TS.t, sim.Stats.frequency, RoundNearest)) < eps(1.0) * sim.TS.t_max
`
Let me know what you think. If we go with the …

support output for dt < 1

---

integration_tests/utils/Cases.jl

`qv` is unused, and the aux diagnosed quantities in initialize profiles are overwritten in the subsequent call to `satadjust`.

Remove unused variable, remove overwritten computations

---

src/Operators.jl
src/Turbulence_PrognosticTKE.jl
src/diagnostics.jl
src/dycore_api.jl
src/update_aux.jl

I just realized that we were using `_tc` for the turbconv dycore api. I think I'd prefer that these methods are verbose, since they're things that the host model will be required to overload, and they should be clear and descriptive.

Use turbconv instead of tc in dycore api

---

src/Turbulence_PrognosticTKE.jl

The momentum diffusivity is used for u and v. AFAIK the computation is actually correct, it was just incorrect aliases.

Fix momentum diffusivity typos.

---

src/update_aux.jl

We should not use environment buoyancy - that is diagnosed from updraft buoyancy - as alternative. Moreover if area is smaller than minimum aux updraft values already default to grid mean in update_aux 55

fix the use of env_b from previous timestep in buoyancy extrap

---

src/Turbulence_PrognosticTKE.jl
src/update_aux.jl

This PR:
- Reduces allocations by reusing existing clima core fields
- Fixes some names
- Inlines `update_updraft` and `update_precipitation`
- Fuses some loops

Reduce allocations

---

integration_tests/utils/main.jl
src/EDMF_Precipitation.jl
src/Turbulence_PrognosticTKE.jl
src/types.jl

This PR
- Makes several precipitation variables ClimaCore fields
- Removes unused functions
I think that, for now, we can keep these tendencies (which are effectively saved for diagnostics) in `aux`. In the long run, I envision having functions that we can accumulate tendencies inside `compute_tendencies`, and they can be computed separately (using the same machinery) in the diagnostics.

Make precip variables ClimaCore fields, rm unused funcs, cleanup

---

integration_tests/utils/Cases.jl
integration_tests/utils/initial_conditions.jl
integration_tests/utils/main.jl
src/Surface.jl
src/turbulence_functions.jl
src/update_aux.jl

This PR
- Makes virtual temperature a ClimaCore field
- Renames θ_ρ -> θ_virt
- Moves `θ_virt` computation in `free_convection_windspeed` to initialization, and re-use computation from `update_aux!` (saves a call to saturation adjustment in some cases).

Make virtual temperature a ClimaCore field

---

integration_tests/utils/Cases.jl
src/Forcing.jl
src/Turbulence_PrognosticTKE.jl
src/types.jl

I removed a few unused lines of code, improved naming of the tendencies and defined what these tendencies are following Shen et al (2021).

Clean up, document LES driven forcing.

---

integration_tests/utils/main.jl
src/EDMF_Environment.jl
src/EDMF_Updrafts.jl
src/Turbulence_PrognosticTKE.jl
src/diagnostics.jl
src/dycore_api.jl
src/io.jl
src/types.jl

This PR makes some rain variables ClimaCore fields, and removes the `UpdraftThermodynamics` struct. Peeled off from #506.

Make some rain variables ClimaCore fields

---

integration_tests/utils/main.jl
src/EDMF_Environment.jl
src/Turbulence_PrognosticTKE.jl
src/diagnostics.jl
src/types.jl

Peel off from #506 - moves environment precipitation related data structures to aux. 
(does not affect RiCO)

move env_thermo precip arrays to aux

---

integration_tests/utils/Cases.jl
integration_tests/utils/main.jl
src/Surface.jl
src/Turbulence_PrognosticTKE.jl
src/turbulence_functions.jl
src/update_aux.jl

This PR converts some variables to ClimaCore fields in the aux state, so that they're not dynamically allocated during tendency evaluations.

Reduce allocations, move some variables to climacore fields

---

integration_tests/ARM_SGP.jl
integration_tests/Bomex.jl
integration_tests/DYCOMS_RF01.jl
integration_tests/DryBubble.jl
integration_tests/GABLS.jl
integration_tests/GATE_III.jl
integration_tests/LES_driven_SCM.jl
integration_tests/Nieuwstadt.jl
integration_tests/Rico.jl
integration_tests/SP.jl
integration_tests/Soares.jl
integration_tests/TRMM_LBA.jl
integration_tests/life_cycle_Tan2018.jl
test/runtests.jl

This PR adds the `@time` macro to the call to `run`, which should hopefully be non-allocating. This should make it easier to monitor allocations as we start to move all allocations outside of the tendency computation function.

Time runs, which should be, ideally, non-allocating

---

integration_tests/utils/Cases.jl
src/Fields.jl
src/types.jl

We can now get rid of `center_field`! 🎉  ~This PR also removes get/set index support for the face-`k` indices (since they're no longer used), so that nobody can accidentally put them back in.~ We can't get rid of that support yet, since we still grab data from arrays in some surface routines.

Cleanup unused methods

---

integration_tests/utils/generate_namelist.jl

In some cases I may want to
1. generate a default namelist for a case, without needing to saving it to file, or
2. specifying another location than `pwd` to store it to.
This PR resolves both issues.

feat: add storage options to `default_namelist`

---

diagnostics/compute_diagnostics.jl
integration_tests/utils/main.jl
perf/allocs.jl
perf/common.jl
src/diagnostics.jl
src/dycore_api.jl

This PR moves the purely diagnostic computations outside of `src/`. This will effectively prevent #468 from reemerging (since we won't have access to these fields inside `src/`).
This is going to cause a bunch of conflicts with the ODE branch, but I think that we can perhaps do that a bit more incrementally.

Move purely diagnostic fields outside of src

---

integration_tests/utils/main.jl
perf/common.jl
src/Turbulence_PrognosticTKE.jl
src/types.jl

This is a prep PR for #473. This PR
- renames `update` to `step!`
- Changes the `step!` interface to be compatible with OrdinaryDiffEq.jl
- Moves the `State` definition into TC.jl `src/`, so that we can pass its properties into a local struct and continue using the dycore API

Change update interface, rename to step

---

diagnostics/compute_diagnostics.jl
docs/src/PlotReferenceStates.jl
integration_tests/utils/main.jl
src/diagnostics.jl

This is a peel-off from #473. Basically, this PR changes the diagnostics dict field entry from a reference to the input state to a function that accepts the state. As a result, `io_dictionary_diagnostics`,`io_dictionary_aux`, etc. do not need the input state, and the dict acts in a more functional way.

Make diag dict field entry a state-accepting func

---

integration_tests/utils/mse_tables.jl
src/closures/buoyancy_gradients.jl
src/types.jl

This PR makes the `EDMF_PrognosticTKE` add a type parameter for `EnvBuoyGradClosure`, to fix the type instability. This was causing a cascade of type inference failures leading up to computing `MinDisspLen`.

Make EDMF model more concrete

---

integration_tests/utils/main.jl
src/update_aux.jl

This was peeled off from #563. This should help to locally check to see the difference between the old/new operators.

Make more variables climacore fields

---

integration_tests/utils/mse_tables.jl
src/EDMF_Precipitation.jl
src/Grid.jl

This should help us avoid calling `collect` when traversing the grid, resulting in fewer memory allocations.

Add iterator for traversing grid

---

src/update_aux.jl

This PR passes `n_updrafts` as a type parameter so that we can potentially unroll some updraft loops. In addition, we avoid calling `ntuple` where it's not necessarily needed.

Try to improve type inference

---

integration_tests/utils/main.jl
src/Turbulence_PrognosticTKE.jl

This PR replaces the use of in-house operators with ClimaCore operators. This should make it easier to refactor the subsequent lines that use `ccut_downwind` and `c∇_downwind`.

Use more ClimaCore operators

---

integration_tests/ARM_SGP.jl
integration_tests/Bomex.jl
integration_tests/DYCOMS_RF01.jl
integration_tests/DryBubble.jl
integration_tests/GABLS.jl
integration_tests/GATE_III.jl
integration_tests/LES_driven_SCM.jl
integration_tests/Nieuwstadt.jl
integration_tests/Rico.jl
integration_tests/SP.jl
integration_tests/Soares.jl
integration_tests/TRMM_LBA.jl
integration_tests/life_cycle_Tan2018.jl
integration_tests/utils/main.jl
integration_tests/utils/post_run_tests.jl
test/runtests.jl

This PR moves the error on early aborted simulations to _after_ the solution is exported. This way we can more easily look at the solution / data to see what went wrong. [Discussed here](https://github.com/CliMA/TurbulenceConvection.jl/issues/574#issuecomment-972920070).
I'm hoping that this will shed light on #577.

Error on aborted simulations after solution export

---

src/Turbulence_PrognosticTKE.jl
src/update_aux.jl

This PR tries to improve inference by improving inference, and fixes some variable names to conform to our naming conventions.

Try to improve inference

---

src/Turbulence_PrognosticTKE.jl

Use more ClimaCore operators, in `compute_covariance_entr`

Use ClimaCore operators

---

driver/main.jl
perf/common.jl
src/Turbulence_PrognosticTKE.jl

@yairchn and @trontrytel pointed out that `step!` is misleading, and I agree. This PR changes the name to `∑tendencies!`.

Change step name to sum tendencies

---

driver/main.jl

quick-fix to convert the `general_ent_params` parameter to an SVector after being read from file. This is required for the `isbits` check in parameter_set.jl:L89 to succeed:
https://github.com/CliMA/TurbulenceConvection.jl/blob/2bc91f6b63c4de7919827040cb74cb58633d16db/driver/parameter_set.jl#L88-L93
The PR fixes an issue where TC.jl will error if run from terminal since reading of lists in the namelist file is converted to a general Array, not a static SVector.
fixes a bug introduced in #635.

fix: convert namelist arrays to SVector

---

post_processing/mse_tables.jl

This PR removes `qt_mean` and `QTvar_mean` comparisons for GABLS because `qt` is zero in the GABLS paper.

Remove moisture comparison in GABLS to fix CI

---

utils/print_new_mse.jl

We've had frequent CI failures lately. So, this PR makes printing the updated MSE tables a bit more robust-- we should be able to see tables for any case that finishes (rather than no tables if even one case fails).

Make printing mse tables more robust

---

perf/invalidations.jl

Missed in #673. I'm not sure how to suppress the output in the `SnoopCompile.invalidation_trees(invalidations)` call.

Add explicit show to last tree element

---

perf/flame.jl

~This PR adds a script / job that saves an svg of a flame graph using `SnoopCompileCore.@snoopi_deep` for Bomex. This should help with monitoring compilation / inference so that we can track how upcoming changes affect performance.~
This PR adds a script to plot flame graphs. It's a bit too expensive to save these graphs to SVG files, but ProfileView.view seems to work fine. So we can just perform this analysis offline.

Add flame graph script to perf folder

---

.github/workflows/TagBot.yml

This PR adds a changelog to the tagbot, so that we don't need to manually go through the PRs for the release notes. I'm not sure if the strings need an exact match or not (e.g., `'bug' in in issue.labels`, where the label may be `bug :bug:`).

Add changelog to TagBot GHA

---

Project.toml
driver/callbacks.jl

I noticed that GHA CI was breaking, and realized that `@inbounds` is suppressed for those simulations because it's run using `Pkg.test()`. It looks like I made an indexing error in #670. This PR extracts `Δz` for cell centers and cell faces, which are needed for two different loops.

Fix CFL dz bug

---

diagnostics/compute_diagnostics.jl
driver/callbacks.jl
driver/initial_conditions.jl
driver/main.jl
src/EDMF_Updrafts.jl
src/Turbulence_PrognosticTKE.jl
src/io.jl
src/types.jl

This PR removes the cloud base, cloud top, and cloud cover from various data structures and computes them on-the-fly in  `compute_diagnostics!`. This allows us to make some of the types immutable.
This PR also removes the `n_updrafts` field from the `UpdraftVariables` struct and puts it in the type space so that loops are able to be unrolled.

Move cloud base, top, and cover to diagnostics

---

src/EDMF_Environment.jl
src/types.jl

`a, w = FastGaussQuadrature.gausshermite(en_thermo.quadrature_order)` runs through a relatively complicated looking code path. I think it's fast because it's fully precompilable, but it takes a surprising amount of space on the flame graph in the tendencies evaluation, so this PR caches it and moves it to initialization.

Cache gauss quad in sgs env thermo

---

src/EDMF_Environment.jl
src/update_aux.jl

This PR manually inlines `update_sat_unsat` and `update_env_precip_tendencies`. Inlining `update_sat_unsat` resulted in 1 less inference trigger (from 6 to 5), and `update_env_precip_tendencies` follows a similar pattern of passing `k` (and the full grid state) to a function. If this triggers runtime inference, then it may happen at every `k` level, which is potentially very bad.

Reduce number of inference triggers

---

diagnostics/compute_diagnostics.jl
driver/Cases.jl
perf/inference_triggers.jl
src/EDMF_Environment.jl
src/EDMF_Precipitation.jl
src/EDMF_Updrafts.jl
src/Grid.jl
src/NetCDFIO.jl
src/Turbulence_PrognosticTKE.jl
src/update_aux.jl

In efforts to further reduce inference triggers, I tried [Cthulhu-ing](https://github.com/JuliaDebug/Cthulhu.jl) into `solve`, and while these changes do not further reduce the inference triggers, `Cthulhu` seems to throw fewer warnings / `Any`s. So, let's merge this. The code hoisting is coming along for the ride.

Rm CCO redef, more type space, +hoist, type annot

---

driver/Cases.jl
driver/generate_namelist.jl
src/Turbulence_PrognosticTKE.jl
src/types.jl
src/update_aux.jl

This PR removes several unused EDMF variables-- some are
- simply never assigned / used
- only assigned then never used
- never used, but also appear as InternalClimaParameters (search `ICP.`)
This PR gets us a reasonable step towards immutable types. We only have
- `SurfaceBase` (may be a bit tough)
- `CasesBase` (should be relatively easy once `SurfaceBase` is immutable)
- `sde_struct` (being fixed in #682)
- `EDMF_PrognosticTKE` (for which `dt_max` is the only remaining mutating field)
I imagine `edmf.zi = get_inversion(grid, state, param_set, surface.Ri_bulk_crit)` is the most controversial removal, but it's not used! I think `zi` is computed locally and used in other places on the fly, which is perfectly fine.

Remove several unused edmf variables

---

diagnostics/compute_diagnostics.jl
driver/Cases.jl
driver/callbacks.jl
driver/initial_conditions.jl
driver/main.jl
perf/common.jl
src/Turbulence_PrognosticTKE.jl
src/types.jl
src/update_aux.jl

This is a prep PR for making `SurfaceBase` immutable (by splitting it into separate types that contain surface constants, and revamping methods for computing other surface variables).

Improve func findability, hoist code, renaming

---

driver/generate_namelist.jl
integration_tests/LES_driven_SCM.jl

This will allow us to use `generate_namelist.jl` (for most cases) without an internet connection 🙂

Move use of ArtifactWrappers inside function

---

src/stochastic_closures.jl
src/types.jl

Mutable structs are not allowed on the GPU, and this one doesn't seem to be used AFAICT. Is this okay, @haakon-e?

Make sde closure immutable

---

driver/Cases.jl
src/Surface.jl
src/types.jl

It turns out that by setting 'qsurface=0' gabls can use MoninObukhov and obtain the same result (i.e. lhf=0) only by virtue of qsurface=0.

remove the DryMoninObukhov surface option

---

perf/pgd.jl

This PR adds a script for profile-guided despecialization. We can't add a buildkite job for this because adding PyPlot seems to break things, but let's just add the script for running things offline.

Add script for profile-guided despecialization

---

.buildkite/pipeline.yml
perf/alloc_per_case_with_init_io.jl
perf/allocs.jl
perf/common.jl

This PR adds a job that more exhaustively tracks allocations (in TC.jl, and all of its _direct_ dependencies) for a shortened simulation.

Add exhaustive allocation tracking job

---

src/Grid.jl
src/Turbulence_PrognosticTKE.jl
src/closures/perturbation_pressure.jl
src/turbulence_functions.jl
src/types.jl
src/update_aux.jl

This PR changes things so that we compute `updraft_top` on the fly. Advantages: we're guaranteed to use the latest information (which resulted in the bugfix in #716), and autodiff may work without issues. In addition, doing this for the remaining arrays in `EDMF_PrognosticTKE` will result in `EDMF_PrognosticTKE` becoming `isbits`, which means it will be gpu compatible.

Compute updraft_top on-the-fly

---

driver/generate_namelist.jl
driver/initial_conditions.jl
driver/main.jl
driver/parameter_set.jl
src/Turbulence_PrognosticTKE.jl
src/turbulence_functions.jl
src/types.jl
src/update_aux.jl

This PR:
- Fixes an inconsistency in the critical Richardson number, which was hardcoded in one of the functions.
- Exposes Ri_c and Pr_t for calibration by moving them to the EDMF_Turbulence_... dictionary. These are after all empirical values.
- Gets Ri_c and a few other parameters from ClimaParameters.
- Exposes kappa_star^2, which was previously hardcoded.

Expose parameters, enforce consistency.

---

.buildkite/pipeline.yml
docs/bibliography.bib
driver/Cases.jl
driver/generate_namelist.jl
integration_tests/DYCOMS_RF02.jl
post_processing/Artifacts.toml
post_processing/compute_mse.jl
post_processing/mse_tables.jl
utils/print_new_mse.jl

This adds a drizzling Sc test case. Currently the LES data is generated with SB microphysics scheme. Once I'm done with implementing the CliMA 1-moment scheme we should switch the dataset

Add DYCOMS_RF02 case

---

test/runtests.jl

Our GHA CI is broken from removing use of `LOAD_PATH` because `Pkg` is not part of TurbulenceConvection's deps. This broke because bors doesn't depend on GHA CI, which is fine.

Fix GHA CI

---

src/closures/entr_detr.jl
src/types.jl
src/update_aux.jl
src/variables.jl

This PR preps some of the entr-detr modeling.
We are duplicating some code here, we could alternatively change the original code to accept the pi groups, if that would help simplify the second part of the entr-detr closure. Regardless, this should help encapsulate / overload the existing entr-detr closures

Allow for non-local entr-detr models

---

driver/main.jl
perf/flame.jl
perf/precompilable_no_init.jl
perf/precompilable_no_init_io.jl

This PR widens the allocation monitoring to the entire `step!` function. To see allocations outside of TC.jl, we'll need to send additional directories to Coverage.jl, and it's a bit tricky due to how environments are configured, so I'll leave that for later.

Widen allocation monitoring

---

driver/compute_diagnostics.jl
driver/generate_namelist.jl
src/closures/entr_detr.jl
src/closures/nondimensional_exchange_functions.jl
src/diagnostics.jl
src/types.jl
src/variables.jl

This PR: 
1.) Adds a nonlocal NN entr closure type
2.) Adds outputs to stats file needed to compute Pi groups offline and validate new closures
3.) Addresses division by 0 in one of the Pi groups 
4.) Fixes a bug affecting several entrainment-related outputs.

Add nonlocal NN entr closure, fix entr bugs

---

post_processing/compute_mse.jl
utils/move_output.jl

Our CI is currently broken because the cluster has been cleaned out, which is fine as the file system was building up quite a bit. So, let's restart things by ensuring that all of our tests pass and we can move the current main results onto the cluster.
**This pr short circuits our regression tests and must be reversed to avoid allowing all prs to automatically pass ci.** No other PRS should be allowed to merge in the mean time.

Let CI pass

---

src/EDMF_Environment.jl

~In efforts of reducing dependence on `Cent`, we're trying to replace our `real_center_indices`/`real_face_indices` loops with broadcast expressions. One place where we have such a loop is in `src/EDMF_Environment.jl`, which happens to also be a part of the code that we'd like to try improving w.r.t. performance (it costs  about 20-30% of `∑tendencies!`).~
I spoke with @trontrytel, and we decided that renaming some of the other variables would be better in a separate PR since it affects many other places in the code. So this PR now only has the some small non-controversial name changes.

Refactor `src/EDMF_Environment.jl`

---

driver/Surface.jl
driver/callbacks.jl
driver/compute_diagnostics.jl
driver/dycore.jl
driver/initial_conditions.jl
driver/main.jl
src/EDMF_Precipitation.jl
src/EDMF_functions.jl
src/update_aux.jl

I think this should make inter-oping with a dycore easier.

Reduce use of GridMeanVariables in TC

---

driver/Cases.jl
driver/Radiation.jl
driver/callbacks.jl
driver/compute_diagnostics.jl
driver/dycore.jl
driver/main.jl
perf/common.jl
perf/jet.jl
src/EDMF_functions.jl
src/types.jl
src/update_aux.jl

It's probably just easier to remove this for now, and we can build up what the host atmos model looks like as we go.
This PR removes GridMeanVariables, which was basically serving as a wrapper for the parameter set.

Remove GridMeanVariables

---

docs/src/PlotReferenceStates.jl
driver/Cases.jl
driver/dycore.jl
driver/main.jl

This is a sub-step to refactor `surface_params` so that it doesn't require the entire state.

Make reference_params return a thermo state

---

driver/dycore.jl
src/EDMF_functions.jl

I accidentally moved some of these functions into `compute_turbconv_tendencies!`, when they are generally something the dycore should call, not edmf.

Unfuse some TC tendency functions

---

integration_tests/3dBomex.jl

This PR synchronizes the spaces on which we're operating on, and calls TC.jl for each column in the 3D Bomex driver. It looks like this same approach should work on a sphere, as far as I can tell.
The next steps are:
- Synchronize the variable names (and types)
- Develop some way to visualize the results
- Start actually debugging the physics
Regarding debugging the physics, we could actually start by just using TC.jl's dycore functions, and run 100 identical columns. From here, we can extract out the dycore pieces outside of the column loop and then try coupling the columns.

Synchronize spaces, call TC.jl

---

driver/generate_namelist.jl
driver/main.jl
driver/parameter_set.jl
src/ClimaParams.jl
src/closures/entr_detr.jl
src/closures/nondimensional_exchange_functions.jl
src/types.jl
src/variables.jl

This Pr:
1.) Generalizes NN construction for arbitrary fully-connected architectures. 
2.) Changes default local NN to have 2 hidden layers. 
3.) Adds a namelist option for flexibly specifying Pi groups. 
4.) Adds 2 new pi groups -> `z/(updraft top)` & `z/(scale height of reference state)`

change default NN to 2-layer network, generalize NN construction

---

driver/generate_namelist.jl
driver/main.jl
src/diagnostics.jl

This flag may give us pretty significant performance improvements in calibration since it will effectively skip out on exporting ~90 fields at the io frequency.
I forget if this is the complete set of needed fields or not, maybe someone can confirm?

Add calibrate_io namelist bool

---

perf/alloc_per_case.jl
perf/benchmark.jl
perf/common.jl
perf/profile.jl

Creating the `params` tuple inside `update_n` may account for some allocations in the benchmark. This PR should
- make our benchmarks a bit more precise.
- widens our allocation monitoring from `∑tendencies!` to `step!` (for which codecov doesn't seem to find any new entries)

Make benchmark more precise, remove update_n

---

Project.toml
driver/callbacks.jl
driver/main.jl
perf/common.jl

I made a flame graph from CalibrateEDMF's julia parallel (pmap) integration test, and it seem that we're somehow paying a pretty steep price for some of the diagnostics. This PR adds `calibrate_io` bool to `Simulation1d` to conditionally skip some of the computations and IO that are not needed for calibration.

Skip some computations / io for calibrate_io

---

perf/allocs.jl
post_processing/compute_mse.jl
utils/move_output.jl

The buildkite account has changed, and so has the default folder, so we need to re-kickstart our CI. The second commit in this PR should be reverted immediately as it will automatically allow our regression tests to pass.
I've also removed the `OrdinaryDiffEq` and `StochasticDiffEq` in allocation monitoring because the depot isn't working correctly with the new directories in the `perf` environment. This should be reverted, too.

Change cluster data prefix

---

driver/generate_namelist.jl
src/closures/entr_detr.jl
src/types.jl

- Adds the 1/m (i.e., identity) dimensional scaling option for entrainment/detrainment non dimensional outputs.
- Fixes function name.

Add (1/m) scaling to entrainment closure.

---

.gitignore
docs/Manifest.toml
integration_tests/3dBomex.jl
integration_tests/SP.jl
integration_tests/baroclinic_wave.jl
integration_tests/driver.jl
perf/Manifest.toml
perf/allocs.jl
perf/common.jl
perf/pgd.jl
test/Manifest.toml
test/runtests.jl

This should make our CI a bit more reproduceable. We'll no longer get auto-upgrades (in our test suite), but we've been hitting a few too many bumps lately.
I believe that I've effectively reproduced the manifest in [this commit](https://github.com/CliMA/TurbulenceConvection.jl/commit/0fe1038a0d224dfa7fe6e77fc52755b3072c2fb8) since it was one of the more recent working set of versions.

Check test, perf, and docs manifests into the repo

---

.buildkite/pipeline.yml

This PR adjusts our buildkite pipeline to be a bit more compact, and apply buildkite groups, so that we can more easily navigate from the top of the buildkite UI. I've removed the keys because it seems like they're only needed when applying dependencies. Our dependencies are mostly in only a few chunks (init, run tests, print mse, move results).

Group pipeline steps

---

perf/allocs.jl

I'm not sure why, but after buildkite directories have changed, our depot isn't working for the perf environment with `OrdinaryDiffEq` and `StochasticDiffEq`. Perhaps, notably, we're not saving a manifest there like we do with our test env. Perhaps we should add it (not just to fix, but maybe it's a good idea regardless).

Add ODE+SDE back into alloc monitor

---

driver/callbacks.jl
driver/compute_diagnostics.jl
driver/main.jl
src/diagnostics.jl

@costachris pointed out that we actually need some computations in `compute_diagnostics!`. Arguably, the variables in those aux fields should be moved into a diagnostics array instead, so that we can make better guarantees about not having simulation results depend on diagnostics. For now, I think this is a quick fix to enable using `calibrate_io`.

Fix scope of calibrate_io, add more fields

---

.gitignore

This PR fixes the .gitignore to ensure the `integration_tests` manifest stays checked into the repo.

Fix gitignore for integration test manifest

---

.dev/up_deps.jl
.gitignore

This PR adds a `.dev/up_deps.jl`, which we can use for upgrading the manifest files according to their compat entries. To keep compat entries synchronized, I created a development package which I plan to register, [CompatDevTools.jl](https://github.com/charleskawczynski/CompatDevTools.jl), which has a function `synchronize_compats(pkg_dir::String)` that we can use. This way, we can monitor / update compat entries in the `integration_tests/` environment, and then use `CompatDevTools.synchronize_compats` to synchronize the other environments.
This PR also adds `test/Manifest.toml` to the git ignore and removes some other entries (I missed that the original manifest entry only applies to the pkgdir, and not using a `*` pattern).

Fix git ignore, add up_deps script to dev folder

---

integration_tests/driver.jl
perf/alloc_per_case.jl
perf/benchmark.jl
perf/benchmark_step.jl
perf/inference_triggers.jl
perf/invalidations.jl
post_processing/case_kwargs.jl

This PR moves the MSE code loading to after the call to `main`. Interesting, this resulted in exposing a race condition which presents itself as a netCDF error:
```
ERROR: LoadError: NetCDF error: NetCDF: String match to name in use (NetCDF error code: -42)
--
  | Stacktrace:
  | [1] check
  | @ /central/scratch/esm/slurm-buildkite/turbulenceconvection-ci/depot/cpu/packages/NCDatasets/c8XyT/src/errorhandling.jl:27 [inlined]
  | [2] nc_def_var(ncid::Int32, name::String, xtype::Int64, dimids::Vector{Int32})
  | @ NCDatasets /central/scratch/esm/slurm-buildkite/turbulenceconvection-ci/depot/cpu/packages/NCDatasets/c8XyT/src/netcdf_c.jl:1389
  | [3] defVar(ds::NCDatasets.NCDataset{NCDatasets.NCDataset{Nothing}}, name::String, vtype::DataType, dimnames::Tuple{String}; …
```

Move mse code loading to after solve, add prefixes for each job

---

.buildkite/pipeline.yml
integration_tests/artifact_funcs.jl
integration_tests/download_artifacts.jl

A long time ago, we decided to add a flag in ArtifactWrappers, `local_run`, which allows users to make a temporary download folder to avoid race conditions (downloading Artifacts is not safe to race conditions). The problem is that this basically completely side-steps the utility of lazily downloading the artifacts on remote machines. So, right now, users leverage the utility of Artifacts because the `local_run` flag we have set to `isempty(get(ENV, "CI", ""))`, which is true on buildkite and GHA CI, but all of CI infra is downloading these artifacts on every build.
This PR changes this by doing a proper lazy download during the initial `steps` in the buildkite pipeline (which happens in serial, but avoids the race condition). The advantage of this is that the very first time we do this, …

Make artifacts download lazily

---

perf/flame_io.jl

This PR adds a flame graph script to analyze io performance. Here's what we're starting how it currently looks:
@Alexander-Barth, why is `size(::NCDataset)` so expensive? This is happening in the call [here](https://github.com/CliMA/TurbulenceConvection.jl/blob/0b7af151696b717bd5c82c81b68a02400704e3d1/driver/NetCDFIO.jl#L149)

Add flame graph script for io

---

integration_tests/Artifacts.toml

I think we missed this in #876, this PR adds the artifacts toml to `integration_tests/`. So, I think we're now still technically downloading on every push, but only once in the `download_artifacts` job. This should fix that and avoid downloads from now on. We should probably clean up any artifact `toml` files that are not used.
(I realized this from running an example locally)
Hmm, actually, the download portion of the job is still taking ~2 min, I may need to play around with this to make sure, or we'll see if the init ever fails due to long download times.

Check in artifacts toml

---

docs/src/PlotReferenceStates.jl
driver/NetCDFIO.jl
driver/compute_diagnostics.jl
driver/main.jl

This PR:
- Renames `path_plus_file` to `nc_filename`
- Makes the inner constructor for `NetCDFIO_Stats` an outer constructor, because I'd like to decouple this data structure from the namelist so that we can later improve io management
- Deletes some `NetCDFIO_Stats` properties that seem to be unused:
- `last_output_time`
- `uuid`
- `stats_path`
- opens and closes files fewer times

Further refactor io

---

driver/NetCDFIO.jl
driver/compute_diagnostics.jl
driver/main.jl
src/diagnostics.jl

This PR makes reference profiles not rely on `write_field`, as a small step towards removing our dependence on `NetCDFIO_Stats`.

Refactor IO

---

integration_tests/Artifacts.toml
integration_tests/driver.jl

Lately I've been seeing that the artifact toml file needs to be updated. This PR updates the artifacts toml and adds a cleanup after the driver, since running TC tends to create this file

Update artifacts toml, add cleanup to driver

---

.buildkite/pipeline.yml
driver/generate_namelist.jl
driver/main.jl
integration_tests/driver.jl
src/Grid.jl

In this PR we added an option for `GeneralizedExponentialStretching` with a grid realistic for a GCM. To make sure that the stretch grid in all cases uses similar points (to each case's vertical domain) the stretch grid is generated first for the GCM domain (45km) and we added a function `TCMeshFromGCMMesh` that takes a subset of that domain relevant for each case (i.e. 400m for GABLS and 17km for TRMM). This stretching effects the results of several cases and for now it is not the default, but appears in an addition Bomex base.

Try stretched grids

---

driver/main.jl

Comments out the stack trace print introduced in PR #862, since it makes debugging very difficult, as discussed in #868 .

Revert full stack trace introduced in PR #862

---

.github/workflows/UpDeps.yml
docs/Manifest.toml
integration_tests/Manifest.toml
perf/Manifest.toml

Right now we depend on users randomly enforcing that dependencies are updated when opening PRs, which can lead to conflicts between merged code and locally (correctly) ran code.
This PR implements a CI workflow that monitors whether all manifests are up to date when staging a PR.

Monitor dependencies are updated

---

README.md
docs/make.jl
docs/src/API.md
docs/src/Formulation.md
docs/src/PlotReferenceStates.jl
docs/src/ReferenceStates.md
docs/src/dev.md
docs/src/index.md

This PR:
- Moves the README table to the developer docs (I wrote this when trying to understand the equations)
- Moves the index.md contents to a newly added API.md, where we can have/add doc string links
- Adds Formulation.md, where we can add (perhaps some from the EDMFEquations.md) a story of the EDMF formulation including figures and equations
- Silences the printed statements in ReferenceStates.md

Add and update some docs and doc stubs

---

driver/Cases.jl
driver/main.jl

I would like to make the LES driven SCM case read grid specs from the LES file so that we can switch from shallow to deep convection cfsites easily in calibration. The main issue is that we need to read the LES grid before most of the LES data is read which makes it a bit messy -- happy to solicitude ideas for to make it better.

read grid specs from LES when LES driving is used

---

.buildkite/pipeline.yml
driver/NetCDFIO.jl
integration_tests/cli_options.jl
integration_tests/driver.jl

This PR refactors the CLI options by:
- Adding explicit flags for skipping post-processing and tests
- Using ArgParse.jl's parsing
@trontrytel, I've removed the `run_from_command_line` flag, but I think we can use `@isdefined parsed_args` to make REPL development easier. Once we create a `parsed_args`, we can reset any of the args to whatever we'd like:
```julia
parsed_args["entr"] = "FNO"
```
This should make #929 much easier to get working without piling on more hacks.

Refactor cli options

---

.buildkite/pipeline.yml
integration_tests/cli_options.jl
integration_tests/driver.jl

I'm impressed that this is working out of the box! Are there other things we could add to visualization? I'm curious (and suspect) what the distribution is of different variables between updrafts.
This PR adds a `n_up` cli option, and fixes a pretty big bug introduced in #932 (parsed args were set to cli options, and not the other way around) 😬.

Add multiple updraft buildkite job

---

.buildkite/pipeline.yml
driver/generate_namelist.jl
integration_tests/cli_options.jl
integration_tests/driver.jl
src/types.jl

This PR:
- adds more command line options (I need them for adding the upcoming #928 to the CI)
- unifies the `["turbulence"]["EDMF_PrognosticTKE"]["env_buoy_grad"]` and the `["thermodynamics"]["sgs"]` namelist flags. This ensures that the buoyancy gradients and environmental sources are computed consistently either on the mean or the quadrature points.

Add to the cli options, unify env_buoy_grad and sgs

---

.buildkite/pipeline.yml
driver/Surface.jl
driver/compute_diagnostics.jl
driver/dycore.jl
driver/generate_namelist.jl
driver/initial_conditions.jl
integration_tests/cli_options.jl
src/EDMF_Environment.jl
src/EDMF_Precipitation.jl
src/EDMF_Updrafts.jl
src/EDMF_functions.jl
src/microphysics_coupling.jl
src/thermodynamics.jl
src/types.jl
src/update_aux.jl
src/variables.jl

This is a draft PR with the non-equilibrium moisture model. The general description of what we are trying to do is here: https://www.overleaf.com/read/hgzwbvbfkqzw
This PR implements the first step from the above document. It (only) adds the non-equilibrium moisture to the updraft equations (equation (7) from the above document). It doesn't do anything about the second order terms related to the cloud liquid and cloud ice variables. This means we are limiting ourselves to not using the quadratures for the buoyancy gradients and the sgs source terms in the environment.
I made sure to code it as an option for `TC.jl`. I don't expect to use it in "operational" `TC.jl` simulations soon. But it is a very interesting research project led by @jbphyswx . 
It would be great if @yairchn and …

Optional non-equilibrium moisture model

---

driver/Surface.jl
driver/compute_diagnostics.jl
driver/dycore.jl
src/update_aux.jl

A followup to #947, #946, and #945.
This PR is technically behavior changing because our thermo states constructed in Surface.jl used to not depend on the equilibrium model (and will depend on the equilibrium model in this PR). Specifically, the calls: `TD.PhaseEquil_pθq(param_set, p0_c_surf, θ_liq_ice_gm_surf, q_tot_gm_surf)`.
We may not need to update the MSE tables, however, since we don't have regression tests for non-vanilla experiments.

Use cached thermo state field more

---

docs/Manifest.toml
driver/generate_namelist.jl
driver/main.jl
integration_tests/Manifest.toml
perf/Manifest.toml
post_processing/mse_tables.jl

Enforce definition of nz or dz in LESdrivenSCM, not both. The behavior before this PR accepted a definition of `nz`, but discarded it silently, which is misleading to users.
The current implementation allows defining either nz or dz.

Enforce definition of nz or dz in LESdrivenSCM, not both.

---

driver/main.jl

This PR creates a standalone function for the construction of the SCM grid from the namelist. This allows users to construct the grid without having to run the model.

Compartmentalize grid construction into standalone function.

---

driver/main.jl
post_processing/mse_tables.jl

Fixes the LES domain height fetch. In PyCLES, the centers precede the faces:
z_half = [Δz/2, Δz + Δz/2, ..., z_max - Δz/2]
z = [Δz, 2Δz, ..., z_max]
Therefore, to get the domain height, we need to fetch the last element of z, not of z_half.

Fix LES domain height fetch

---

.buildkite/pipeline.yml

This PR removes the develop step. We shouldn't need this since we're checking in the Manifest.
@yairchn, this should fix the issues you're having.

Remove Pkg.develop in build

---

integration_tests/cli_options.jl
integration_tests/driver.jl
integration_tests/truncate_stack_traces.jl

Who wants shorter stack traces? 📒 This PR truncates printing for ClimaCore Field types (which people may know can be pretty long).

Truncate printing of ClimaCore field types

---

integration_tests/driver.jl
src/EDMF_functions.jl
src/types.jl
src/variables.jl

This PR adds error checking to the CL arguments to prevent silently running unexpected configurations. This requires that we keep two lists up to date: `overwrite_namelist_map` (which we already had) and `no_overwrites` (now added). Before running, we now check that we've overwritten the correctly prescribed number of CL arguments.
This PR also attempts to fix the case that uses the nonequilibrium model, which we forgot to add to the `overwrite_namelist_map`.
~It seems like it's not yet working, but I made some changes that I'm not sure about.~ Looks like it's working!

Add error checking to CL overwrites

---

driver/parameter_set.jl

This PR adds the non-equilibrium moisture parameters to edmf namelist and allows to easily overwrite them. 
To run non-equilibrium simulations those settings need to be changed in the namelist file
```
namelist["thermodynamics"]["moisture_model"] = "nonequilibrium"             
namelist["thermodynamics"]["sgs"] = "mean"                                                       
```
To test different relaxation timescales additionally change this
```
namelist["microphysics"]["τ_cond_evap"] = 42.0                              
namelist["microphysics"]["τ_sub_dep"] = 44.0 
```

add non-eq params to edmf parameter_set and namelist

---

driver/Cases.jl
driver/Radiation.jl
driver/dycore.jl
integration_tests/3dBomex.jl
integration_tests/baroclinic_wave.jl
src/types.jl

The motivation for this PR is organizing and making a clear distinction between the various large scale tendencies in the various cases. Currently, several cases mix the application of advective and radiative tendencies. This has no effect when `θ_liq_ice` is the prognostic variable and both tendencies are applied in the same way. When `e_tot` is the prognostic variable however these two tendencies need to be applied differently, i.e. acting on total enthalpy (with `c_pm`) or on total energy (with `c_vm`).
* I removed `dTdt` and `dqtdt` in `aux_gm` as it is ambiguous and resorted to use `dTdt_hadv` and `dqtdt_hadv` instead. 
* The flag `apply subsidence` is not needed anymore as in cases where subsidence should not be applied the subsidence velocity is simply zero anyways.

Separate large scale advective from radiative tendencies

---

docs/src/API.md
src/EDMF_Precipitation.jl
src/EDMF_functions.jl
src/ExperimentalClimaParams.jl
src/InternalClimaParams.jl
src/TurbulenceConvection.jl
src/closures/buoyancy_gradients.jl
src/closures/entr_detr.jl
src/closures/mixing_length.jl
src/closures/nondimensional_exchange_functions.jl
src/closures/perturbation_pressure.jl
src/microphysics_coupling.jl
src/turbulence_functions.jl
src/update_aux.jl

As suggested by Issue https://github.com/CliMA/TurbulenceConvection.jl/issues/997 this adds `InternalClimaParams.jl` as a way to interface with the default parameters of CliMA. The already existing `ClimaParameters.jl` file (with experimental params that are not yet part of CliMAParameters) is now renamed to `ExperimentalClimaParams.jl`.
HTH with moving parameters around!

Add internal clima parameters

---

.buildkite/pipeline.yml
driver/compute_diagnostics.jl
driver/generate_namelist.jl
driver/main.jl
integration_tests/3dBomex.jl
integration_tests/baroclinic_wave.jl
integration_tests/cli_options.jl
integration_tests/driver.jl
src/microphysics_coupling.jl
src/types.jl

In response to issue https://github.com/CliMA/TurbulenceConvection.jl/issues/1009
This PR:
- fixes the `rho_cloud_liquid` problem by using the `CliMAParameters.jl` defined liquid water density
- adds TRMM + cutoff microphysics to Vanilla + Deviations tests in the buildkite CI
- renames `CutoffPrecipitation` precipitation model to `Clima0M` precipitation model. This is done to be more consistent with the notation used in the `CloudMicrophysics.jl` package.

fix cutoff precipitation

---

driver/Cases.jl
driver/dycore.jl
driver/generate_namelist.jl
driver/main.jl
src/types.jl
src/utility_functions.jl

The GCM relaxation is different for deep convective cases. This PR specifies different relaxations in `Cases.jl` in a manner consistent with the LES runs.

add relaxation for deep convective LES_driven_SCM cases

---

driver/Cases.jl
driver/dycore.jl
driver/main.jl

This is a peel off PR from #960. This PR:
- Moves the prognostic initialization from Cases to a call to a newly added function, `set_prog_from_aux!`, which we can potentially dispatch on later with different energy variables.

Move prog init from Cases to dycore func

---

.buildkite/pipeline.yml
driver/generate_namelist.jl
driver/parameter_set.jl
integration_tests/cli_options.jl
integration_tests/driver.jl
src/EDMF_Environment.jl
src/EDMF_Precipitation.jl
src/EDMF_Updrafts.jl
src/ExperimentalClimaParams.jl
src/microphysics_coupling.jl
src/types.jl
src/update_aux.jl

This PR adds a precipitation fraction model. The supported options are:
- prescribed (done via experimental parameter, defaults to precipitation_fraction = 1, which is what we have now)
- diagnostic based on the max cloud fraction (it has an experimental parameter that limits the precip fraction to to be smaller than the limiter value)
The basic idea is to divide the precipitation variables by the precip fraction before computing any source terms with them. And then multiply by precip fraction at the end to recover back the grid mean tendency. The non-linearities in the microphysics source terms should make a difference compared to precipitation fraction = 1
Edit: After some discussions with @yairchn and @ilopezgp we decided to apply this only to source terms. We need to think more on how …

Add prescribed and diagnostic precip fraction

---

driver/compute_diagnostics.jl

We need to calibrate and validate to the water path diagnostics, without a need for fluxes etc that slow down IO.
This PR allows writing to file the `xWP` diagnostics to file even if calibrate_io.

Write water paths to file if calibrate_io

---

.buildkite/pipeline.yml
Project.toml
driver/callbacks.jl
driver/compute_diagnostics.jl
driver/main.jl
integration_tests/cli_options.jl
integration_tests/driver.jl
src/diagnostics.jl

This PR
- Fixes the currently broken `calibrate_io = true` non-vanilla test
- Adds a `broken_test` CL argument, since some other non-vanilla tests are broken too (and bails before testing that the simulation has not crashed)
- Moves the testing that simulations have not crashed immediately after solving, so that all tests, not just vanilla tests, have this sanity check.

Test that CI does not crash for non-vanilla cases

---

src/update_aux.jl

This reverts https://github.com/CliMA/TurbulenceConvection.jl/pull/1018
Right now we are inconsistent and taking `p[k]` for equilibrium `ts` but `p[k-1]` for non-equilibrium `ts`. 
Also, taking `p[k-1]` results in no updrafts for shallow convection cases and delays TRMM convection by around an hour.  (Compare the buildkite artifacts from before and after merging https://github.com/CliMA/TurbulenceConvection.jl/pull/1018 when looking at TRMM with non-equilibrium moisture model)

Fix non-equilibroum buoyancy calculations

---

src/Grid.jl
test/clima_core_extensions.jl

This PR allows us to build a grid given a space, so that our internal space (for `z`-coordinates) are indistinguishable from other fields.

Construct grid with spaces

---

.buildkite/pipeline.yml

I'm finding that the RF test is very brittle (e.g., in #1074 and #1062). We can add it back in once that model is initialized with sensible values.

Make RF broken test true

---

perf/benchmark.jl
perf/benchmark_step.jl

We currently don't limit the number of samples in our benchmark, which is problematic for cases that are not intended to be run past a certain time. This PR limits the samples based on the final time and dt.

Limit benchmark samples

---

integration_tests/driver.jl

This PR adds a condition around `(s, parsed_args) = parse_commandline()`, so that users can use something like
```julia
using Revise
include("integration_tests/cli_options.jl");
(s, parsed_args) = parse_commandline();
parsed_args["config"] = "sphere";
include("integration_tests/driver.jl")
```
To run the driver with their own configured parsed args. I have been continually doing this and then commenting the first few driver lines to run cases locally.

Conditionally compute parsed args

---

driver/callbacks.jl
driver/main.jl
integration_tests/driver.jl

- Synchronize first io call within main for all profiles and time series.
- Fixes #821 and #897.
- Tests for filled values in integration tests, which were not covered previously (hence the errors).
- Initializes integrator during initialization, and passes it as an argument to `run`.

Limit io to callbacks, sync profiles and timeseries (v2)

---

driver/dycore.jl
src/EDMF_functions.jl
src/Fields.jl
src/closures/entr_detr.jl

This PR fixes the TODO:
```julia
Base.:-(a::FT, b::CCG.Covariant3Vector{FT}) where {FT} = a .- b.u₃
Base.:+(a::FT, b::CCG.Covariant3Vector{FT}) where {FT} = a .+ b.u₃
```
by removing this overloading.
Closes #1022.

Remove overloading +- for Covariant3Vectors

---

driver/NetCDFIO.jl
driver/TimeStepping.jl
driver/compute_diagnostics.jl
driver/main.jl
integration_tests/Manifest.toml

This PR fixes some type instabilities, and makes the code a bit more type-generic. I also ran `resolve`, which added `Random` to the Manifest. This was missed in #1097.
A step towards #133.

Fix some type instabilities, make code more type-generic

---

src/types.jl

This is needed to keep the EDMF model `isbits` for typical cases.

Wrap entr_pi_subset in Tuple in edmf constructor

---

driver/Cases.jl
driver/main.jl
src/types.jl

I just realized that we no longer use `inversion_type`, can we remove it?

Remove inversion types

---

driver/initial_conditions.jl
src/types.jl

When looking to refactor the code, I realized that `aux_tc.prandtl_nvec` is initialized, but then overwritten (before ever being used) in `update_aux!`. This PR removes the unused initialization. Doing this resulted in `prandtl_number` being unused, so this PR also removes this variable. `prandtl_number` was initialized to `namelist["turbulence"]["EDMF_PrognosticTKE"]["Prandtl_number_0"]`, but that is still used in the code as a clima parameter.

Remove unused initialization and variable

---

perf/precompilable_no_init.jl

It looks like we're a bit too close to this limit (see [this build](https://buildkite.com/clima/turbulenceconvection-ci/builds/10975)).

Bump precompilation time speedup test

---

.buildkite/pipeline.yml

This PR changes/fixes with buildkite flag for the Bomex with Gaussian quadrature test.
The model very well may work fine if the namelist were properly set, this bug is specific to specifying the CL overwrites.
I'm going to re-push once #1121 merges.

Fix buildkite job for Bomex with Gaussian

---

driver/callbacks.jl
driver/compute_diagnostics.jl
driver/dycore.jl
driver/main.jl
perf/common.jl
src/EDMF_functions.jl
src/types.jl

This PR
- Removes CasesBase, which was basically a form of the host atmos model, so it living in TC's src was a bit awkward.
- Only pass CasesBase properties into functions that are needed, this will help make initialization more flexible and alleviates scope assumptions

Remove CasesBase

---

src/thermodynamics.jl

We're no longer using `total_enthalpy` and `kinetic_energy`. Also, the way we compute `kinetic_energy` has now changed due to the vector types. This was missed in #1100.

Clean up unused functions

---

driver/Cases.jl
driver/Radiation.jl
driver/Surface.jl
driver/compute_diagnostics.jl
driver/dycore.jl
driver/initial_conditions.jl
driver/main.jl
src/EDMF_Precipitation.jl
src/EDMF_functions.jl
src/closures/entr_detr.jl
src/closures/perturbation_pressure.jl
src/types.jl
src/update_aux.jl

This PR adds `float_type(::State)`, and we grab `FT` from it everywhere. This peels off quite a bit of stuff from the ForwardDiff-compatible branch.

Get FT from float_type (added)

---

Project.toml
docs/Manifest.toml
integration_tests/Manifest.toml
perf/Manifest.toml

We need another patch release for theta-var (including the fix to overwriting the precipitation tendencies with zeros)

bump version for a patch release

---

integration_tests/cli_options.jl

This PR splits up the print repl script so that we can get not just the repl script, but also the parsed args for each job.

Split up print repl script

---

integration_tests/driver.jl
integration_tests/overwrite_namelist.jl

This PR moves all of the namelist overwrite logic and logging into a separate function, so that we can more easily configure non-vanilla jobs for other analysis (e.g., performance).

Move overwrite namelist into a separate function

---

integration_tests/cli_options.jl
src/Fields.jl

This PR:
- Removes an unused method, `set_z!`, which I forgot to remove in #1173.
- Fixes a sub/super type bug: need to use `val isa AbstractString` in `print_repl_script`.

Fix subtype bug, remove unused method definition

---

driver/Cases.jl
driver/main.jl
src/types.jl

This PR:
- Removes hard-coded `Float64`, and makes `ForcingBase` and `RadiationBase` type-generic
- Removes some `ForcingBase` outer constructors, and fallback on the abstract type case, instead. This is possible because of several previous refactoring changes that resulted in most of the `ForcingBase` definitions to be nearly unified.
- Converts the `EDMFModel` from an inner constructor to an outer constructor. This may be helpful for @dennisYatunin when experimenting with Duals.
I still need to try changing our duals test so that we use Float64 in the EDMF model and apply type promotions where needed, however, this may take some time so let's merge this in first.

Fix type instabilities

---

src/closures/nondimensional_exchange_functions.jl
src/types.jl

A step towards closing #1177. This PR moves the `reshape` in the RF model into the initialization, and moves some size information into the `RFEntr` type space. This is done to ensure that the compiler has access to the sizes.

Reshape arrays at init, parameterize array dims

---

integration_tests/cli_options.jl

This PR makes `parsed_args_from_command_line_flags` more flexible by allowing users to pass in `parsed_args`, so that it can return either the entire set of args, or the overwrites only.

Make parsed_args_from_cl_flags more flexible

---

src/Grid.jl

The value-per-column space was moved to `make_hybrid_spaces` to synchronize with ClimaAtmos. This PR removes the now unused value-per-column space in Grid.

Remove unused point space

---

.buildkite/pipeline.yml
driver/NetCDFIO.jl
driver/callbacks.jl
driver/main.jl

This PR changes our duals test to fully run with duals: we will run (and test) the exact same vanilla Bomex case with Float64 and with Dual numbers.
If our duals test pass (our duals simulation output will be compared with the results from the vanilla Bomex), then everything regarding running TC with duals should be fine on the TC side. cc @dennisYatunin.
Next, I'll try initializing EDMFModel with Float64, but I'm not exactly sure how many changes that this will require.

Fully run duals test

---

integration_tests/cli_options.jl

A mirror of [CA#560](https://github.com/CliMA/ClimaAtmos.jl/pull/560).
This should fix the `"true""` in this REPL script:
```julia
using Revise; include("integration_tests/cli_options.jl");
(s, parsed_args) = parse_commandline();
parsed_args["case"] = "Bomex";
parsed_args["dt_max"] = 8.0;
parsed_args["suffix"] = "_n_up_2";
parsed_args["n_up"] = 2;
parsed_args["skip_tests"] = "true"";
include("integration_tests/driver.jl")
```

Fix parsed_args_from_cl_args

---

driver/main.jl

It seems that 'unstable_check_kwarg(::Cases.LES_driven_SCM)' is not needed anymore

remove the stability check of LES_driven_SCM in the ode solver

---

Project.toml

- Minor release of theta-var branch that includes the MSE reference state fix, which should enable calibration of the deep convective cases without spurious results near the tropopause.

Update to 0.27.6 (fixed reference state)

---

.buildkite/pipeline.yml
driver/common_spaces.jl
integration_tests/cli_options.jl

This PR:
- Adds the truncated GCM mesh capability back in
- Changes that test to run `LES_driven_SCM` (cc @trontrytel, @ilopezgp)
- Adds a doc string snippet to `print_repl_script`

Add truncated GCM mesh back in

---

driver/callbacks.jl
driver/compute_diagnostics.jl
driver/dycore_variables.jl
driver/main.jl
src/closures/nondimensional_exchange_functions.jl

- Merges #1217 to main branch,
- Merges #1229 to main branch,
- Adds back the `calibrate_io` clause, which seems to have been deleted. Was this intentional @charleskawczynski ? Are we missing it in other parts of the code?
- Benefit: Potentially return to the main branch for research purposes.

Add most missing pieces from theta-var.

---

driver/common_spaces.jl
src/Grid.jl

The current truncated mesh represents a truncation of the GCM mesh that retains enough elements of the GCM mesh to cover the entire requested space, without modifying the mesh points. This means that if a `z_top=4000.0` is requested, the last element of `TC.Grid(mesh).zf.z` is greater or equal than 4000.0, but may be e.g. 4200.0. This causes inconsistencies in the forcing of different benchmarks. How do we force/initialize beyond the original domain? The answer is non-trivial, case-specific and prone to error.
The new truncated mesh retains the number of degrees of freedom or the original truncated mesh, but recomputes the stretch necessary to reach `z_top` exactly. This means that in the end we have  `vec(`TC.Grid(mesh).zf.z`)[end] == 4000.0`.
Avoids serious problems in the definition of …

Correct grid truncation by enforcing z_top.

---

Project.toml

- Minor release set to substitute the theta-var series v0.27.x

Bump main to v.034, potential candidate to deprecate v0.27.x

---

docs/Manifest.toml
integration_tests/Manifest.toml
perf/Manifest.toml

I need to use the patch version of CloudMicrophysics.jl `v0.7.1`. I ran the `up_deps` script.

Update the deps for CM.jl patch release 0.7.1

---

.buildkite/pipeline.yml
Project.toml
driver/generate_namelist.jl
driver/main.jl
integration_tests/cli_options.jl
integration_tests/overwrite_namelist.jl
src/EDMF_Environment.jl
src/EDMF_Updrafts.jl
src/TurbulenceConvection.jl
src/microphysics_coupling.jl
src/types.jl
src/update_aux.jl

Co-authored-by: lynnyang <lynnyang@caltech.edu>
This PR makes use of 2-moment, prescribed cloud droplet number concentration microphysics schemes in the new release of CloudMicrophysics.jl. On the TC.jl side we are creating a rain model that accepts the prescribed droplet number concentration as argument. The default scheme is unchanged. 
The new keyword options are:
`--rain_formation_scheme` (valid options: `clima_1m_default`, `KK2000`, `B1994`, `TC1980`, `LD2004`)
`--prescribed_Nd` (number of droplets per m3)
See the 2-moment CloudMicrophysics.jl [docs](https://clima.github.io/CloudMicrophysics.jl/dev/Microphysics2M/) for details. 
We will now have more microphysics options. (Uncertain if its a benefit or risk).

Add 2-moment, prescribed Nd autoconversions and accretions

---

Project.toml
src/utility_functions.jl

- Enables the use of CNRM-CM5 LES runs,
- Splits the LES libraries into a shallow library (published in Shen et al 2022), and a bigger library including the experimental deep convection cases.

Add more LES cases for LES_driven_SCM()

---

src/closures/entr_detr.jl
src/types.jl
src/update_aux.jl

separate turb entr to facilitate using two dynamical entr models in a follow up PR (i.e. physical and ml entrainment)

seprate turb entr

---

driver/main.jl
src/closures/nondimensional_exchange_functions.jl
src/types.jl

This is an alternative to #1211. This PR uses `Array`s in the Random Feature model, since large SArrays and Tuples (O(1000)) are _really_ expensive for the compiler. This PR tests out ordinary arrays.
It'll be interesting to compare both the compile time and runtime.

Try using Arrays in RF model

---

perf/allocs.jl

Our allocation analysis is one of the most expensive jobs, and the different cases point to the same locations for allocations, so the job removed is not really showing us anything new.

Remove TRMM from allocs analysis

---

src/utility_functions.jl

Adds the `CNRM-CM6-1` cases to the library of shallow cases allowed for calibration.

Add CNRM-CM6-1 cases

---

src/utility_functions.jl

This fix adds the CNRM-CM6-1 cases to the construction of the general LES dictionary (shallow+deep), which is necessary when assessing whether the requested path is a `valid_lespath`.

Include CNRM-CM6-1 in the acceptable LES_driven_SCM requests.

---

driver/callbacks.jl
driver/dycore.jl
src/types.jl

This PR is a step towards improving inference

Try improving inference

---

driver/callbacks.jl
driver/generate_namelist.jl
src/EDMF_functions.jl
src/Parameters.jl
src/types.jl
src/update_aux.jl
src/variables.jl

Adds a [Lewis](https://en.wikipedia.org/wiki/Lewis_number) number scaling to the moisture diffusivity.
Easy way to make model more flexible, by relaxing the assumption of heat and moisture diffusivity being equal. Instead, we now assume they are proportional.

Add Lewis number scaling for mass diffusivity.

---

driver/compute_diagnostics.jl
driver/generate_namelist.jl
driver/initial_conditions.jl
integration_tests/Artifacts.toml
src/EDMF_functions.jl
src/closures/perturbation_pressure.jl
src/types.jl
src/update_aux.jl

- Adds options for prognostic and closure-based determination of bottom boundary condition on area. For prognostic option, surface area is prognostically determined in the bottom cell center, instead of prescribed as surface_area parameter. For closure option, bottom area determined as a linear function of surface heat fluxes.
-  Initial conditions for prognostic surface area: area fraction and updraft w set to nonzero values in bottom cell center and top face, along with the associated prognostic variables. This initialization is to break symmetry and prevent trivial a = 0, w = 0 solution.
- Swaps order of set_edmf_surface_bc and filter_updraft_vars, since updraft variables are used to compute surface theta and qt fluxes.

Include prognostic and closure options for surface area BC

---

driver/compute_diagnostics.jl
src/EDMF_functions.jl
src/closures/perturbation_pressure.jl
src/update_aux.jl

Explicitly declare InterpolateC2F kwargs for bottom and top boundaries on area.

Explicitly declare InterpolateC2F kwargs

---

driver/Cases.jl
post_processing/mse_tables.jl
src/utility_functions.jl

Remove cfsites 2,3 from shallow les library. These 2 cfSites are not in steady-state (height of SC clouds continue to grow throughout the LES simulation + cause many TC crashes)
Use first timestep (GCM profile) in LES stats file to initalize thetali, qt, u, and v instead of mean LES profiles.

Updates to LES_driven_SCM cases 

---

driver/compute_diagnostics.jl
src/EDMF_functions.jl
src/closures/entr_detr.jl
src/closures/nondimensional_exchange_functions.jl
src/diagnostics.jl
src/types.jl
src/variables.jl

Add massflux gradient entr dimensional scales and modify Pi group definitions. Save pi groups to stats file output and ensure computation for every entr closure type.

Modify Pi groups and include in stats file output
